import {NextRequest,NextResponse} from './http';
import {init,identity,dashboard,createRoom,joinRoom,startRoom,leaveRoom,roomState,submit,advance,requireAccount,requireAdmin,one,many,run,batch,profile,GameError} from '@/lib/game/service';
import {bucket} from '@/db/raw';
import {type Kind,type Locale,normalize} from '@/lib/game/rules';
export const dynamic='force-dynamic';
function json(data:unknown,status=200){return NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function error(e:unknown){if(e instanceof GameError)return json({error:e.message},e.status);throw e}
export async function GET(req:NextRequest){try{await init();const q=req.nextUrl.searchParams,action=q.get('action')||'dashboard';const u=await identity();if(u.signed)await requireAccount();
 if(action==='dashboard')return json(await dashboard(u));
 if(action==='room')return json(await roomState(q.get('id')||'',u));
 if(action==='lobby'){await requireAccount();return json({rooms:await many("SELECT r.id,r.code,r.kind,r.locale,r.created_at,COALESCE(p.name,'Player') AS host_name,(SELECT COUNT(*) FROM members m WHERE m.room=r.id AND m.left_at IS NULL) AS players FROM rooms r LEFT JOIN profiles p ON p.id=r.host WHERE r.mode='multi' AND r.status='waiting' AND r.updated_at>? ORDER BY r.created_at DESC LIMIT 30",Date.now()-3600000)});}
 if(action==='leaderboard'){const week=q.get('period')!=='all';return json({rows:await many("SELECT p.id,p.name,p.avatar,COUNT(*) AS solved,SUM(CASE r.kind WHEN 'mcq' THEN 10 WHEN 'letters' THEN 15 ELSE 20 END) AS points FROM attempts a JOIN rounds rr ON rr.id=a.round JOIN rooms r ON r.id=rr.room JOIN profiles p ON p.id=a.user WHERE a.correct=1 AND a.created_at>=? GROUP BY p.id ORDER BY points DESC,solved DESC,p.name LIMIT 50",week?Date.now()-604800000:0)});}
 if(action==='profile'){const a=await requireAccount();return json({profile:await profile(a.id),stats:await one("SELECT (SELECT COUNT(*) FROM attempts WHERE user=? AND correct=1) AS solved,(SELECT COUNT(*) FROM members WHERE user=?) AS games,(SELECT COUNT(*) FROM rooms r WHERE r.mode='multi' AND r.status='finished' AND (SELECT COUNT(*) FROM rounds WHERE room=r.id AND winner=?)>0 AND NOT EXISTS(SELECT 1 FROM members m WHERE m.room=r.id AND m.user!=? AND (SELECT COUNT(*) FROM rounds WHERE room=r.id AND winner=m.user)>=(SELECT COUNT(*) FROM rounds WHERE room=r.id AND winner=?))) AS wins",a.id,a.id,a.id,a.id,a.id),history:await many("SELECT r.id,r.kind,r.mode,r.status,r.created_at,COUNT(CASE WHEN rr.winner=? THEN 1 END) AS solved,r.total FROM rooms r JOIN members m ON m.room=r.id LEFT JOIN rounds rr ON rr.room=r.id WHERE m.user=? GROUP BY r.id,m.user ORDER BY r.created_at DESC LIMIT 30",a.id,a.id),wallet:await many('SELECT amount,reason,created_at FROM wallet WHERE user=? ORDER BY created_at DESC LIMIT 40',a.id)});}
 if(action==='admin'){await requireAdmin();return json({content:await many('SELECT * FROM content ORDER BY kind,locale,id'),reports:await many('SELECT r.*,c.prompt FROM reports r LEFT JOIN content c ON c.id=r.content_id ORDER BY r.created_at DESC LIMIT 100'),users:await many('SELECT id,name,username,banned,created_at FROM profiles ORDER BY created_at DESC LIMIT 100')});}
 throw new GameError('Unknown request.',404);
 }catch(e){return error(e)}}
export async function POST(req:NextRequest){try{const origin=req.headers.get('origin');if(origin&&origin!==req.nextUrl.origin)throw new GameError('Request origin is not allowed.',403);if(Number(req.headers.get('content-length'))>40000)throw new GameError('Request is too large.');const b:any=await req.json();if(!b||typeof b!=='object'||typeof b.action!=='string')throw new GameError('Invalid request.');await init();const u=await identity();if(u.signed)await requireAccount();
 switch(b.action){
 case 'create':return json(await createRoom(b.kind as Kind,b.locale as Locale,b.mode==='multi'?'multi':'solo',u));
 case 'join':return json(await joinRoom(String(b.code||''),u));
 case 'start':await startRoom(String(b.id),u.id);break;
 case 'leave':await leaveRoom(String(b.id),u.id);break;
 case 'answer':return json(await submit(String(b.id),String(b.roundId),b.answer,u));
 case 'skip':return json(await submit(String(b.id),String(b.roundId),null,u,true));
 case 'next':await advance(String(b.id),u.id,true);break;
 case 'profile':{const a=await requireAccount();const name=String(b.name||'').trim(),username=String(b.username||'').trim().toLowerCase();if(name.length<2||name.length>40)throw new GameError('Display name must be 2 to 40 characters.');if(username&&!/^[a-z0-9_]{3,24}$/.test(username))throw new GameError('Username needs 3 to 24 letters, numbers or underscores.');if(username&&await one('SELECT id FROM profiles WHERE username=? AND id!=?',username,a.id))throw new GameError('Username already used.');await run('UPDATE profiles SET name=?,username=?,country=?,city=?,age_group=?,locale=? WHERE id=?',name,username||null,String(b.country||'').slice(0,80),String(b.city||'').slice(0,80),String(b.age_group||'').slice(0,30),b.locale==='ar'?'ar':'en',a.id);return json({profile:await profile(a.id)});}
 case 'report':{const a=await requireAccount();const message=String(b.message||'').trim();if(message.length<5||message.length>1000)throw new GameError('Describe the issue in 5 to 1,000 characters.');if(!await one('SELECT id FROM content WHERE id=?',b.contentId))throw new GameError('Puzzle not found.');if(await one('SELECT id FROM reports WHERE user=? AND content_id=? AND created_at>?',a.id,b.contentId,Date.now()-60000))throw new GameError('This report was already sent.');await run('INSERT INTO reports(id,user,content_id,message,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),a.id,b.contentId,message,Date.now());break;}
 case 'content':{await requireAdmin();const c=b.content;if(!c||!['mcq','letters','cryptogram'].includes(c.kind)||!['en','ar'].includes(c.locale))throw new GameError('Choose a valid game and language.');if(typeof c.prompt!=='string'||c.prompt.trim().length<3||c.prompt.length>600)throw new GameError('Puzzle text must be 3 to 600 characters.');const choices=Array.isArray(c.choices)?c.choices:[],clues=Array.isArray(c.clues)?c.clues:[];if(choices.some((x:any)=>typeof x!=='string'||!x.trim()||x.length>300))throw new GameError('Enter valid answer choices.');if(c.kind==='mcq'&&(choices.length<2||choices.length>4||!Number.isInteger(Number(c.answer))||Number(c.answer)<0||Number(c.answer)>=choices.length))throw new GameError('Enter 2 to 4 choices and a valid correct-answer number.');if(c.kind==='letters'&&(!c.answer||!c.prompt.toLowerCase().includes(String(c.answer).toLowerCase())||/\s/.test(c.answer)||String(c.answer).length>20))throw new GameError('The missing answer must be one word present in the proverb.');if(c.kind==='cryptogram'&&(clues.length<1||clues.length>12||clues.some((x:any)=>!x.word||!x.hint||String(x.word).length>40||String(x.hint).length>150)))throw new GameError('Add 1 to 12 valid word clues.');const id=c.id||crypto.randomUUID();await run('INSERT INTO content(id,kind,locale,prompt,answer,choices,clues,explanation,active) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,locale=excluded.locale,prompt=excluded.prompt,answer=excluded.answer,choices=excluded.choices,clues=excluded.clues,explanation=excluded.explanation,active=excluded.active',id,c.kind,c.locale,c.prompt.trim(),c.kind==='cryptogram'?c.prompt.trim():String(c.answer),JSON.stringify(choices),JSON.stringify(clues),String(c.explanation||'').slice(0,1000),c.active===0?0:1);return json({id});}
 case 'ban':{const admin=await requireAdmin();if(b.id===admin.id)throw new GameError('You cannot suspend your own account.');await run('UPDATE profiles SET banned=? WHERE id=?',b.banned?1:0,String(b.id));break;}
 case 'archive':await requireAdmin();await run('UPDATE content SET active=? WHERE id=?',b.active?1:0,String(b.id));break;
 case 'resolve':await requireAdmin();if(!['open','reviewing','resolved','rejected'].includes(b.status))throw new GameError('Invalid report status.');await run('UPDATE reports SET status=? WHERE id=?',b.status,String(b.id));break;
 case 'delete':{const a=await requireAccount();if(b.confirm!=='DELETE')throw new GameError('Type DELETE to confirm.');const p=await profile(a.id);if(p?.avatar)await bucket().delete(p.avatar);const rooms=await many("SELECT r.id FROM rooms r JOIN members m ON m.room=r.id WHERE m.user=? AND m.left_at IS NULL",a.id);for(const r of rooms)await leaveRoom(r.id,a.id);await batch([['DELETE FROM attempts WHERE user=?',[a.id]],['DELETE FROM wallet WHERE user=?',[a.id]],['DELETE FROM reports WHERE user=?',[a.id]],['UPDATE rounds SET winner=NULL WHERE winner=?',[a.id]],['DELETE FROM members WHERE user=?',[a.id]],['DELETE FROM profiles WHERE id=?',[a.id]]]);break;}
 default:throw new GameError('Unknown action.',404);
 }return json({ok:true});}catch(e){return error(e)}}
