-- Hikmah content import, round 2, 21 Sep 2026
-- 197 general knowledge MCQ questions (active), 11 letters proverbs (active),
-- 23 letters proverbs staged INACTIVE until the patched hikmah-api (whole-word blank) is deployed.
-- Already applied to production project vilgghdzyqdsvbaazphh. Idempotent.

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-8efac924c722','letters','ar','لا تشترِ خنزيرًا في كيس.','كيس','[]','[]','',1),
('letters-2dbf403da3a7','letters','ar','الآلهة تعين من يعين نفسه.','نفسه','[]','[]','',1),
('letters-e0c85756a1dc','letters','en','Don''t buy a pig in a poke.','poke','[]','[]','',1),
('letters-c71352e3ff76','letters','en','The gods help those who help themselves.','themselves','[]','[]','',1),
('letters-2a9080f224cf','letters','en','A man is as old as he feels, and a woman as old as she looks.','feels','[]','[]','',1),
('letters-ee09d057c80f','letters','en','It is better to rule in hell than serve in heaven.','heaven','[]','[]','',1),
('letters-976382a906ec','letters','en','Give a man enough rope and he will hang himself.','rope','[]','[]','',1),
('letters-947108731a17','letters','en','The person who arrives late at the party must dance with the ugly ones (Russian).','arrives','[]','[]','',1),
('letters-ee09fd36a895','letters','en','Spare the rod and spoil the child.','rod','[]','[]','',1),
('letters-34538eb7e22a','letters','en','Forbidden fruit is the sweetest.','forbidden','[]','[]','',1),
('letters-4da2c50bb57f','letters','en','You can''t make a silk purse out of a sow''s ear.','silk','[]','[]','',1),
('letters-18689b2e778f','letters','ar','لا يُغسل الدم بالدم.','الدم','[]','[]','',0),
('letters-14a1e3d4f84e','letters','ar','لكل كلب يوم، ولكل قط يومان.','يوم','[]','[]','',0),
('letters-fd93e4b4d093','letters','ar','أن تملك ولا تحتاج خير من أن تحتاج ولا تملك.','تحتاج','[]','[]','',0),
('letters-8adf1fab0d39','letters','ar','الأحمق الظريف خير من الظريف الأحمق.','الظريف','[]','[]','',0),
('letters-b7c6e7ac3b84','letters','ar','الشباب يضيع على الشباب.','الشباب','[]','[]','',0),
('letters-3724243f18a2','letters','ar','أعز من الولد ولد الولد','الولد','[]','[]','',0),
('letters-964f47707eca','letters','ar','ليس كل جميل خيرًا لكن الخير جميل دائمًا.','جميل','[]','[]','',0),
('letters-9c4ef2f15766','letters','en','Let bygones be bygones.','bygones','[]','[]','',0),
('letters-f03e12b25610','letters','en','Never say never.','never','[]','[]','',0),
('letters-36d9cbc9ef10','letters','en','The enemy of my enemy is my friend.','enemy','[]','[]','',0),
('letters-0f25096ed6fa','letters','en','Deep doubts, deep wisdom; small doubts, little wisdom.','wisdom','[]','[]','',0),
('letters-efc25c293064','letters','en','What goes around comes around.','around','[]','[]','',0),
('letters-f208abc8cf6b','letters','en','Easy come, easy go.','easy','[]','[]','',0),
('letters-71462e1ebc51','letters','en','To the world you may be one person, but to one person you may be the world.','world','[]','[]','',0),
('letters-03e1c9e983b4','letters','en','When the going gets tough, the tough get going.','tough','[]','[]','',0),
('letters-f4dd4445f1fd','letters','en','A penny saved is a penny earned.','penny','[]','[]','',0),
('letters-a16afb3ee37d','letters','en','An army of sheep led by a lion is better than an army of lions led by a sheep (Arabic).','sheep','[]','[]','',0),
('letters-60a0911c710a','letters','en','Better to have it and not need it than to need it and not have it.','need','[]','[]','',0),
('letters-28bb092f4089','letters','en','A beautiful person is not always good, but a good person is always beautiful (Hungarian).','beautiful','[]','[]','',0),
('letters-10a14a3a7001','letters','en','He who lives by the sword shall die by the sword.','sword','[]','[]','',0),
('letters-f1dfc86d76ba','letters','ar','كل تأخيرة وفيها خيرة','خيرة','[]','[]','',0),
('letters-990455dac9d3','letters','ar','من عاش بالسيف مات بالسيف.','السيف','[]','[]','',0),
('letters-7d72c9c86947','letters','en','In the kingdom of the blind, the one-eyed man is king.','king','[]','[]','',0)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('mcq-11e7691c5aa2','mcq','ar','ما هو الإنترنت؟','0','["شبكة عالمية","جهاز","لغة برمجة","نظام تشغيل"]','[]','',1),
('mcq-38abd4ed3a53','mcq','en','Which is the largest planet in the Solar System?','0','["Jupiter","Saturn","Uranus","Neptune"]','[]','',1),
('mcq-f75948dde2e2','mcq','en','What is the name of Saudi Arabia’s national oil company?','0','["Saudi Aramco","SABIC","Ma’aden","STC"]','[]','',1),
('mcq-2b034afd0609','mcq','en','What is the holy book of Islam?','0','["Quran","Bible","Torah","Vedas"]','[]','',1),
('mcq-fbe94e3b6047','mcq','ar','ما هو المقصود بقاعدة البيانات؟','0','["مكان منظم لتخزين البيانات واسترجاعها","برنامج لتصميم الصور","نظام تشغيل","نوع من المتصفح"]','[]','',1),
('mcq-d4112aacdcde','mcq','ar','أي مما يلي متصفح إنترنت؟','0','["Chrome","Windows","Linux","Android"]','[]','',1),
('mcq-268b95b7b683','mcq','en','What is the main source of energy for Earth?','0','["Sun","Moon","Wind","Ocean"]','[]','',1),
('mcq-dac22e64b070','mcq','ar','أي من هذه المدن تشتهر بزراعة الورد الطائفي؟','0','["الطائف","حائل","تبوك","القصيم"]','[]','',1),
('mcq-578d55cb850d','mcq','ar','من بنى سور الصين العظيم؟','0','["الصينيون","الرومان","المغول","الفرس"]','[]','',1),
('mcq-d133d20c6d52','mcq','en','What is the official currency of Saudi Arabia?','0','["Saudi riyal","Kuwaiti dinar","UAE dirham","Qatari riyal"]','[]','',1),
('mcq-57e16d3b1956','mcq','en','How many days are in a leap year?','0','["366","365","364","360"]','[]','',1),
('mcq-28dd645f8dad','mcq','en','Which is the world’s largest onshore oil field located in Saudi Arabia?','0','["Ghawar","Safaniya","Shaybah","Abqaiq"]','[]','',1),
('mcq-dab841664e62','mcq','ar','أي مما يلي يُعد لغة استعلام لقواعد البيانات؟','0','["SQL","HTML","CSS","PNG"]','[]','',1),
('mcq-c64e086a771b','mcq','en','What is net profit?','0','["Revenue minus costs","Total sales","Capital","Debt"]','[]','',1),
('mcq-c1f93d725475','mcq','ar','كم عدد أركان الإسلام؟','0','["خمسة","أربعة","ستة","سبعة"]','[]','',1),
('mcq-afbc460615e8','mcq','ar','ما الخليج الذي يحد المملكة من الشرق؟','0','["الخليج العربي","خليج عمان","خليج العقبة","خليج السويس"]','[]','',1),
('mcq-5931d4a01768','mcq','ar','كم عدد سور القرآن الكريم؟','0','["114","112","110","120"]','[]','',1),
('mcq-9b16b7b49601','mcq','ar','ما المقصود بالمخزون؟','0','["السلع الجاهزة للبيع","الأرباح","الديون","الرواتب"]','[]','',1),
('mcq-3e2e0009c8f7','mcq','en','What is the approximate value of 7 × 8?','0','["56","48","64","52"]','[]','',1),
('mcq-9217ba615f87','mcq','en','Which is the largest offshore oil field in Saudi Arabia?','0','["Safaniya","Ghawar","Khurais","Shaybah"]','[]','',1),
('mcq-b811112bc30c','mcq','ar','ما اسم الشهر الذي يصوم فيه المسلمون؟','0','["رمضان","شوال","محرم","ربيع الأول"]','[]','',1),
('mcq-94b0fca28acc','mcq','ar','في أي قارة تقع البرازيل؟','0','["أمريكا الجنوبية","أمريكا الشمالية","أوروبا","أفريقيا"]','[]','',1),
('mcq-1f879c72fb6d','mcq','ar','ما اسم المؤسس الأول للدولة السعودية الثالثة (المملكة العربية السعودية)؟','0','["الملك عبدالعزيز آل سعود","الملك سعود بن عبدالعزيز","الملك فيصل بن عبدالعزيز","الإمام محمد بن سعود"]','[]','',1),
('mcq-431f24240628','mcq','ar','ما فائدة النسخ الاحتياطي؟','0','["استعادة البيانات عند فقدانها","تسريع الإنترنت","زيادة سعة الشاشة","إيقاف التحديثات"]','[]','',1),
('mcq-cbf6e9cc95ee','mcq','en','What planet is known as the Red Planet?','0','["Mars","Venus","Mercury","Jupiter"]','[]','',1),
('mcq-7e40dbb7bc98','mcq','ar','ما أطول نهر في العالم؟','0','["النيل","الأمازون","الفرات","الدانوب"]','[]','',1),
('mcq-185e8fb2b306','mcq','en','What organ pumps blood through the human body?','0','["Heart","Lungs","Liver","Kidneys"]','[]','',1),
('mcq-76a940947458','mcq','en','Which city is famous for Taif roses?','0','["Taif","Hail","Jubail","Buraidah"]','[]','',1),
('mcq-b0bc3efbf143','mcq','ar','أي فيتامين يرتبط بأشعة الشمس؟','0','["فيتامين D","فيتامين C","فيتامين A","فيتامين B12"]','[]','',1),
('mcq-923a09ed57a3','mcq','en','Which is a web browser?','0','["Chrome","Linux","Android","Windows"]','[]','',1),
('mcq-e52bd5f5d8e8','mcq','ar','إلى أي جهة يتجه المسلمون في الصلاة؟','0','["الكعبة","القدس","المدينة","دمشق"]','[]','',1),
('mcq-7d95bcb973b6','mcq','ar','ما اسم الخط العربي الذي تشتهر به كسوة الكعبة؟','0','["الثلث","النسخ","الرقعة","الديواني"]','[]','',1),
('mcq-66e6684264ae','mcq','en','What does API commonly mean?','0','["Application Programming Interface","Applied Process Internet","Advanced Public Integration","Active Program Index"]','[]','',1),
('mcq-bcbcab11e201','mcq','en','What is the first surah of the Quran?','0','["Al-Fatiha","Al-Baqarah","Al-Ikhlas","An-Nas"]','[]','',1),
('mcq-80bde9f8a6d9','mcq','en','How many surahs are in the Quran?','0','["114","110","112","120"]','[]','',1),
('mcq-e7f5e04279f6','mcq','ar','في أي عام توحدت المملكة العربية السعودية؟','0','["1932","1925","1918","1945"]','[]','',1),
('mcq-ad9553fd12d5','mcq','en','Which food is high in protein?','0','["Eggs","Sugar","White bread","Butter"]','[]','',1),
('mcq-f7dd16cbb33a','mcq','en','Who conquered Constantinople in 1453?','0','["Mehmed II","Saladin","Caesar","Napoleon"]','[]','',1),
('mcq-b09d5aec8781','mcq','en','What is the capital of Japan?','0','["Tokyo","Kyoto","Osaka","Nagoya"]','[]','',1),
('mcq-311e6fa2ce56','mcq','en','Which city is located on the Red Sea coast?','0','["Jeddah","Dammam","Buraidah","Hofuf"]','[]','',1),
('mcq-9e054cc8218a','mcq','ar','أي من هذه المدن تقع على البحر الأحمر؟','0','["جدة","الدمام","الهفوف","بريدة"]','[]','',1),
('mcq-e0ff11b37cff','mcq','ar','أين قامت الحضارة الفرعونية؟','0','["مصر","العراق","اليونان","الهند"]','[]','',1),
('mcq-01f3e6412741','mcq','en','Which is a query language for databases?','0','["SQL","JPEG","MP3","CSV"]','[]','',1),
('mcq-226bbfabd8cc','mcq','en','How many daily prayers are obligatory in Islam?','0','["5","3","4","6"]','[]','',1),
('mcq-6d6ff93474f1','mcq','en','Where was Mesopotamia located?','0','["Iraq","Egypt","India","China"]','[]','',1),
('mcq-2b40d9cfead2','mcq','ar','ما اسم أول سورة في القرآن؟','0','["الفاتحة","البقرة","العلق","الناس"]','[]','',1),
('mcq-142179cc5c63','mcq','ar','ما أسرع الحيوانات البرية؟','0','["الفهد","الأسد","الحصان","الذئب"]','[]','',1),
('mcq-b33f72764548','mcq','en','Which continent is Japan in?','0','["Asia","Europe","Africa","America"]','[]','',1),
('mcq-7e0c10c795f9','mcq','en','Which city is located on the Arabian Gulf coast?','0','["Dammam","Jeddah","Taif","Abha"]','[]','',1),
('mcq-9b67c6ca00b3','mcq','en','Which of the following is a renewable energy source?','0','["Solar energy","Coal","Oil","Natural gas"]','[]','',1),
('mcq-ed24e66d20d1','mcq','ar','كم عدد عظام جسم الإنسان البالغ؟','0','["206","201","210","198"]','[]','',1),
('mcq-db68b6160990','mcq','ar','أي من هذه المواقع هو موقع أثري في شمال غرب السعودية؟','0','["العلا","جازان","الأحساء","نجران"]','[]','',1),
('mcq-843b7fc2ce0b','mcq','ar','أي مما يلي يُعد من عادات النوم الجيدة؟','0','["النوم في وقت ثابت","شرب منبهات قبل النوم","استخدام الشاشة حتى اللحظة الأخيرة","تجاهل ضوء الصباح"]','[]','',1),
('mcq-2ba5ec13a664','mcq','en','What is the name of the pilgrimage to Makkah?','0','["Hajj","Umrah","Zakat","Salah"]','[]','',1),
('mcq-fa3b3047ae57','mcq','en','What is the longest river in the world?','0','["Nile","Amazon","Yangtze","Danube"]','[]','',1),
('mcq-87923aeab027','mcq','ar','ما الغاز الضروري لعملية التنفس؟','0','["الأكسجين","النيتروجين","الهيدروجين","ثاني أكسيد الكربون"]','[]','',1),
('mcq-152703f8d0ea','mcq','en','What is the capital of Italy?','0','["Rome","Milan","Naples","Venice"]','[]','',1),
('mcq-5855a25fe734','mcq','en','Mount Uhud is located near which city?','0','["Madinah","Riyadh","Jeddah","Abha"]','[]','',1),
('mcq-c7d5f0f90a99','mcq','en','Which continent is the largest by area?','0','["Asia","Africa","Europe","South America"]','[]','',1),
('mcq-f36db47f208c','mcq','en','Which sea borders Saudi Arabia to the west?','0','["Red Sea","Arabian Gulf","Black Sea","Caspian Sea"]','[]','',1),
('mcq-a4ab7cc810c9','mcq','ar','ما هو نظام التشغيل؟','0','["برنامج يدير الجهاز","لغة برمجة","متصفح","قطعة عتاد"]','[]','',1),
('mcq-12f01ac3ff07','mcq','ar','ما اسم اليوم الوطني السعودي؟','0','["23 سبتمبر","1 يناير","22 فبراير","10 رمضان"]','[]','',1),
('mcq-2a42e231b0dd','mcq','ar','ما العضو المسؤول عن ضخ الدم؟','0','["القلب","الرئة","الكبد","المعدة"]','[]','',1),
('mcq-679ab6aac8cd','mcq','en','What organ is responsible for vision?','0','["Eye","Ear","Brain","Skin"]','[]','',1),
('mcq-214cd9994c10','mcq','ar','ما فائدة التخزين السحابي؟','0','["حفظ البيانات عبر الإنترنت","زيادة سرعة المعالج","تبريد الجهاز","تحسين الشاشة"]','[]','',1),
('mcq-c625d4c5fec6','mcq','ar','من هو فاتح القسطنطينية؟','0','["محمد الفاتح","صلاح الدين","طارق بن زياد","هارون الرشيد"]','[]','',1),
('mcq-b55e395ddb60','mcq','en','Which writing style is commonly associated with the calligraphy on the Kaaba’s kiswa?','0','["Thuluth","Gothic","Italic","Kufic"]','[]','',1),
('mcq-dadb0f8ff9b7','mcq','en','What is the capital of Egypt?','0','["Cairo","Alexandria","Luxor","Aswan"]','[]','',1),
('mcq-93b6a98d8201','mcq','en','Which body of water borders Saudi Arabia to the east?','0','["Arabian Gulf","Gulf of Oman","Gulf of Aqaba","Gulf of Suez"]','[]','',1),
('mcq-d005a13085c7','mcq','ar','ما أعلى جبل في العالم؟','0','["إيفرست","K2","الهيمالايا","الألب"]','[]','',1),
('mcq-03b9c15faa88','mcq','ar','ما عاصمة إيطاليا؟','0','["روما","ميلانو","نابولي","فينيسيا"]','[]','',1),
('mcq-a21d62f46ec2','mcq','ar','ما اسم المهرجان السنوي الذي يقام في الجنادرية؟','0','["المهرجان الوطني للتراث والثقافة","موسم الرياض","موسم جدة","مهرجان شتاء طنطورة"]','[]','',1),
('mcq-2ce17e20aeb5','mcq','ar','أي من هذه الأطعمة أعلى غالبا بالألياف؟','0','["البقوليات","السكر","الزبدة","المشروبات الغازية"]','[]','',1),
('mcq-04c7cd4f03eb','mcq','en','Which nutrient is most associated with muscle repair?','0','["Protein","Sugar","Trans fat","Sodium"]','[]','',1),
('mcq-e9515c92b8ce','mcq','ar','ما هو الربح الصافي؟','0','["الإيرادات ناقص التكاليف","إجمالي المبيعات","رأس المال","الديون"]','[]','',1),
('mcq-73b6d48ee6ce','mcq','en','What is an operating system?','0','["Software that manages hardware","A browser","A database","A device"]','[]','',1),
('mcq-24c38d94a4e8','mcq','ar','ما هو الكوكب المعروف بالكوكب الأحمر؟','0','["المريخ","الزهرة","عطارد","المشتري"]','[]','',1),
('mcq-88e3cc83fc9c','mcq','ar','ما فائدة ممارسة الرياضة بانتظام؟','0','["تحسين الصحة العامة","زيادة التوتر","إضعاف المناعة","قلة النوم"]','[]','',1),
('mcq-5e1c93a49830','mcq','ar','كم عدد الصلوات المفروضة يوميا؟','0','["5","4","3","6"]','[]','',1),
('mcq-2909593189fe','mcq','ar','ما فائدة شرب الماء؟','0','["ترطيب الجسم","زيادة الدهون","تقليل التركيز","رفع السكر"]','[]','',1),
('mcq-7989c226f70d','mcq','en','How many rakahs are in Fajr prayer?','0','["2","4","3","1"]','[]','',1),
('mcq-0231d08a5928','mcq','en','How many pillars of Islam are there?','0','["5","4","6","7"]','[]','',1),
('mcq-4558f5e0b22d','mcq','en','What does CPU stand for?','0','["Central Processing Unit","Computer Power User","Control Program Unit","Central Program Utility"]','[]','',1),
('mcq-b7f0111e5851','mcq','ar','ما اسم ليلة نزول القرآن؟','0','["ليلة القدر","ليلة الإسراء","ليلة النصف","ليلة العيد"]','[]','',1),
('mcq-0fd8106df28e','mcq','en','Which festival was historically held at Janadriyah?','0','["National Festival for Heritage and Culture","Riyadh Season","Jeddah Season","Winter at Tantora"]','[]','',1),
('mcq-da4dd324ce7a','mcq','en','Which sea separates Saudi Arabia and Egypt?','0','["Red Sea","Arabian Sea","Mediterranean Sea","Black Sea"]','[]','',1),
('mcq-1db551646e22','mcq','en','How many administrative regions does Saudi Arabia have?','0','["13","10","12","15"]','[]','',1),
('mcq-01dd5ca5a633','mcq','ar','أي مما يلي أصل ثابت؟','0','["المباني","النقد","المخزون","الحسابات المدينة"]','[]','',1),
('mcq-9a9b2f1b3328','mcq','ar','أي من هذه المدن تقع على الخليج العربي؟','0','["الدمام","جدة","الطائف","أبها"]','[]','',1),
('mcq-2bdcf3177f82','mcq','ar','ما عاصمة تركيا؟','0','["أنقرة","إسطنبول","إزمير","أنطاليا"]','[]','',1),
('mcq-f2d1702a4e89','mcq','en','Which is generally high in fiber?','0','["Legumes","Butter","Candy","Soda"]','[]','',1),
('mcq-949445c9a82a','mcq','en','What is capital in business?','0','["Money used to start a business","Profit","Revenue","Taxes"]','[]','',1),
('mcq-db2e8537991b','mcq','en','What is the capital of Turkey?','0','["Ankara","Istanbul","Izmir","Antalya"]','[]','',1),
('mcq-688639152e01','mcq','ar','ما وظيفة المعالج؟','0','["تنفيذ العمليات","تخزين البيانات","عرض الصور","الاتصال بالشبكة"]','[]','',1),
('mcq-8e565a46e664','mcq','ar','في أي قارة تقع اليابان؟','0','["آسيا","أوروبا","أفريقيا","أمريكا"]','[]','',1),
('mcq-b304994a5556','mcq','en','Which planet is closest to the Sun?','0','["Mercury","Venus","Earth","Mars"]','[]','',1),
('mcq-eaf3ccf8f2dd','mcq','en','Which country is the largest by land area?','0','["Russia","China","Canada","United States"]','[]','',1),
('mcq-1d2e78dff0e7','mcq','en','In which year was Saudi Arabia unified?','0','["1932","1920","1945","1918"]','[]','',1),
('mcq-ac8bf8489049','mcq','ar','أي من هذه الغازات هو الأكثر وجودا في الغلاف الجوي للأرض؟','0','["النيتروجين","الأكسجين","ثاني أكسيد الكربون","الهيدروجين"]','[]','',1),
('mcq-e5fad75c2c40','mcq','ar','ما البحر الذي يحد المملكة من الغرب؟','0','["البحر الأحمر","الخليج العربي","بحر العرب","البحر الأسود"]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('mcq-b48ccbdfe6c5','mcq','ar','كم عدد أحرف اللغة العربية؟','0','["28","26","29","30"]','[]','',1),
('mcq-61e810ee42a6','mcq','en','Which vitamin is linked to sunlight?','0','["Vitamin D","Vitamin C","Vitamin A","Vitamin B"]','[]','',1),
('mcq-6f4d1a3aef12','mcq','ar','ما هو العنصر الكيميائي الذي رمزه O؟','0','["الأكسجين","الذهب","الحديد","الأوزميوم"]','[]','',1),
('mcq-e59372e93b19','mcq','en','How many continents are there on Earth?','0','["7","5","6","8"]','[]','',1),
('mcq-6a529472e163','mcq','en','How many letters are in the Arabic alphabet (standard count)?','0','["28","26","29","30"]','[]','',1),
('mcq-175f48eb6eaf','mcq','ar','ما هو أكبر حقل نفطي بحري في السعودية؟','0','["السفانية","الغوار","الخفجي","الشيبة"]','[]','',1),
('mcq-6ce81bfd8f4c','mcq','ar','ما هو رأس المال؟','0','["المال المستخدم لبدء المشروع","الأرباح","الإيرادات","الضرائب"]','[]','',1),
('mcq-2bbff4cc2dc0','mcq','ar','ما الكوكب الأقرب إلى الشمس؟','0','["عطارد","الزهرة","الأرض","المريخ"]','[]','',1),
('mcq-4a40dc15befd','mcq','ar','أين قامت حضارة بلاد الرافدين؟','0','["العراق","مصر","الهند","الصين"]','[]','',1),
('mcq-ab5129237329','mcq','ar','من كان أول رئيس للولايات المتحدة؟','0','["جورج واشنطن","أبراهام لينكولن","توماس جيفرسون","جون آدامز"]','[]','',1),
('mcq-ac9a2f2c6a8c','mcq','ar','ما المقصود بالإيرادات في الأعمال؟','0','["المال الداخل من المبيعات","تكلفة التشغيل","الديون المستحقة","صافي الربح فقط"]','[]','',1),
('mcq-a92c7e013f45','mcq','ar','ما اسم عملية تحول الماء من سائل إلى بخار؟','0','["التبخر","التكاثف","التجمد","الانصهار"]','[]','',1),
('mcq-374ff444a573','mcq','ar','ما هو الناتج التقريبي لـ 7 × 8؟','0','["56","48","64","52"]','[]','',1),
('mcq-1515ed21b14c','mcq','en','Which of these is revenue?','0','["Product sales","Rent","Salaries","Shipping cost"]','[]','',1),
('mcq-9ac8e907c7d7','mcq','ar','أي طعام غني بالبروتين؟','0','["البيض","السكر","الخبز الأبيض","الزبدة"]','[]','',1),
('mcq-79a5b0db3984','mcq','en','What is the capital of France?','0','["Paris","Rome","Berlin","Madrid"]','[]','',1),
('mcq-c8069a84e3a9','mcq','en','What is the name of the vast desert in the south of Saudi Arabia?','0','["Rub al Khali","Sahara","Gobi","Kalahari"]','[]','',1),
('mcq-925675c36e4f','mcq','ar','كم عدد ركعات صلاة الفجر؟','0','["2","3","4","1"]','[]','',1),
('mcq-58d606f2eaae','mcq','ar','كم عدد ساعات النوم الموصى بها للبالغين؟','0','["7-9","4-5","10-12","3-4"]','[]','',1),
('mcq-f30bcb519242','mcq','ar','كم عدد القارات في العالم؟','0','["7","5","6","8"]','[]','',1),
('mcq-1e2969395e78','mcq','ar','ما اسم الشركة الوطنية السعودية للنفط والغاز؟','0','["أرامكو السعودية","سابك","معادن","STC"]','[]','',1),
('mcq-2375bef17a92','mcq','ar','أي مما يلي يُعد تكلفة ثابتة عادة؟','0','["الإيجار","المواد الخام","الشحن لكل طلب","عمولة المبيعات"]','[]','',1),
('mcq-a655fa41bd46','mcq','ar','ما هي عاصمة اليابان؟','0','["طوكيو","كيوتو","أوساكا","ناغويا"]','[]','',1),
('mcq-50337045d13d','mcq','ar','ما اسم آخر سورة في القرآن؟','0','["الناس","الفلق","الإخلاص","الكافرون"]','[]','',1),
('mcq-fa7ee5338a25','mcq','ar','أي مما يلي يُعد إيرادا؟','0','["مبيعات المنتجات","إيجار المكتب","رواتب الموظفين","تكلفة الشحن"]','[]','',1),
('mcq-1439caaa08bc','mcq','ar','أين يقع جبل أحد؟','0','["المدينة المنورة","الرياض","الطائف","أبها"]','[]','',1),
('mcq-bf3eccba49b4','mcq','ar','ما هو أكبر حقل نفطي بري في العالم يقع في السعودية؟','0','["الغوار","السفانية","الشيبة","بقيق"]','[]','',1),
('mcq-043d1414478b','mcq','ar','أي مما يلي نظام تشغيل؟','0','["Android","Chrome","Google","HTML"]','[]','',1),
('mcq-2dabf2565dba','mcq','ar','ما هي عاصمة فرنسا؟','0','["باريس","روما","برلين","مدريد"]','[]','',1),
('mcq-cbbcb65efbe2','mcq','ar','ما اسم العملة الرسمية في المملكة العربية السعودية؟','0','["الريال السعودي","الدينار الكويتي","الدرهم الإماراتي","الريال القطري"]','[]','العملة الرسمية هي الريال السعودي.',1),
('mcq-5897bf43b615','mcq','ar','ما وحدة قياس التيار الكهربائي؟','0','["الأمبير","الفولت","الأوم","الواط"]','[]','',1),
('mcq-231b03803cfb','mcq','ar','من هو أول خليفة في الإسلام؟','0','["أبو بكر الصديق","عمر بن الخطاب","عثمان بن عفان","علي بن أبي طالب"]','[]','',1),
('mcq-770ece5b5800','mcq','ar','ما عاصمة المملكة العربية السعودية؟','0','["الرياض","جدة","الدمام","أبها"]','[]','',1),
('mcq-bb34767ebc7a','mcq','en','What is the largest ocean on Earth?','0','["Pacific Ocean","Atlantic Ocean","Indian Ocean","Arctic Ocean"]','[]','',1),
('mcq-1796e7ee38a9','mcq','en','Which historic city is considered the cradle of the first Saudi state?','0','["Diriyah","AlUla","Jeddah","Abha"]','[]','',1),
('mcq-3f0db5d1dbda','mcq','en','Which gas is most abundant in Earth’s atmosphere?','0','["Nitrogen","Oxygen","Carbon dioxide","Hydrogen"]','[]','',1),
('mcq-782d7f48d245','mcq','en','Which site is a major archaeological destination in northwestern Saudi Arabia?','0','["AlUla","Jazan","Al Hofuf","Najran"]','[]','',1),
('mcq-57268a025ee1','mcq','ar','ما اسم كتاب المسلمين المقدس؟','0','["القرآن","الإنجيل","التوراة","الزبور"]','[]','',1),
('mcq-a2fad014657a','mcq','en','Where did the ancient Egyptian civilization arise?','0','["Egypt","Mesopotamia","India","China"]','[]','',1),
('mcq-05ec0a7c0fd0','mcq','ar','ما هي عاصمة مصر؟','0','["القاهرة","الإسكندرية","الأقصر","أسوان"]','[]','',1),
('mcq-83bb0f1aa599','mcq','en','Which is an operating system?','0','["Android","HTML","CSS","USB"]','[]','',1),
('mcq-d772807e96d9','mcq','ar','ما اسم أطول صحراء رملية متصلة في المملكة؟','0','["الربع الخالي","صحراء النفود","الدهناء","صحراء سيناء"]','[]','',1),
('mcq-26819b839425','mcq','ar','ما الهدف من نقطة التعادل؟','0','["معرفة متى تغطي الإيرادات التكاليف","رفع السعر تلقائيا","تقليل عدد العملاء","زيادة المخزون"]','[]','',1),
('mcq-b52d683bb303','mcq','en','How many hours of sleep are recommended for adults?','0','["7-9","5-6","10-12","3-4"]','[]','',1),
('mcq-94bd9ca6e285','mcq','en','What gas do humans need to breathe?','0','["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"]','[]','',1),
('mcq-88480bfcc668','mcq','ar','أي مما يلي هو أكبر محيط على الأرض؟','0','["المحيط الهادئ","المحيط الأطلسي","المحيط الهندي","المحيط المتجمد الشمالي"]','[]','',1),
('mcq-c00bfe199c75','mcq','ar','أي بحر يفصل بين السعودية ومصر؟','0','["البحر الأحمر","بحر العرب","الخليج العربي","البحر المتوسط"]','[]','',1),
('mcq-b33e5c9b32f7','mcq','en','Who was the first caliph in Islam?','0','["Abu Bakr","Umar","Uthman","Ali"]','[]','',1),
('mcq-11b520ede7a3','mcq','ar','كم عدد المناطق الإدارية في المملكة العربية السعودية؟','0','["13","10","12","15"]','[]','تتكون المملكة من 13 منطقة إدارية.',1),
('mcq-d8ab7e07730a','mcq','ar','أي مدينة تُعد مهد الدولة السعودية الأولى؟','0','["الدرعية","الرياض","جدة","العلا"]','[]','',1),
('mcq-23a01135b95f','mcq','ar','ما اسم قبلة المسلمين الأولى؟','0','["المسجد الأقصى","الكعبة","المسجد النبوي","المسجد الحرام"]','[]','',1),
('mcq-d6e5fe6abbdd','mcq','en','What is the process of liquid water turning into vapor called?','0','["Evaporation","Condensation","Freezing","Melting"]','[]','',1),
('mcq-fe55b70f3725','mcq','ar','ما اسم أطول وادٍ في السعودية ضمن هذه الخيارات؟','0','["وادي الرمة","وادي حنيفة","وادي الدواسر","وادي بيشة"]','[]','',1),
('mcq-e5d7d58d876f','mcq','en','What is Saudi Arabia’s National Day date?','0','["September 23","January 1","May 5","December 2"]','[]','',1),
('mcq-fe8c599dff21','mcq','ar','ما هي أكبر دولة في العالم من حيث المساحة؟','0','["روسيا","الصين","كندا","الولايات المتحدة"]','[]','',1),
('mcq-7b92496a0d89','mcq','ar','ما مصدر الطاقة الأساسي للأرض؟','0','["الشمس","القمر","الرياح","المحيطات"]','[]','',1),
('mcq-d448f26697b5','mcq','ar','ما المقصود بالتدفق النقدي؟','0','["حركة المال الداخل والخارج","الأرباح فقط","الضرائب","المخزون"]','[]','',1),
('mcq-4d7f02e7cd5a','mcq','ar','أي مما يلي يعد من مصادر الطاقة المتجددة؟','0','["الطاقة الشمسية","الفحم","النفط","الغاز الطبيعي"]','[]','',1),
('mcq-2b7ebe802e1c','mcq','en','What does ROI stand for?','0','["Return on Investment","Rate of Inventory","Revenue on Income","Risk of Interest"]','[]','',1),
('mcq-9e7d6c82fa9a','mcq','ar','كم عدد أيام السنة الكبيسة؟','0','["366","365","360","364"]','[]','',1),
('mcq-8de5a772e7bf','mcq','en','What does cash flow describe?','0','["Money in and out","Profit only","Taxes","Inventory"]','[]','',1),
('mcq-2551b8550f29','mcq','ar','ما العضو المسؤول عن الرؤية؟','0','["العين","الأذن","الدماغ","الجلد"]','[]','',1),
('mcq-e5db7f005827','mcq','en','What is the chemical symbol for oxygen?','0','["O","Ox","Og","On"]','[]','',1),
('mcq-3520a263ab68','mcq','ar','أي من هذه المناطق تُعرف بواحة الأحساء؟','0','["المنطقة الشرقية","منطقة مكة","منطقة عسير","منطقة الجوف"]','[]','',1),
('mcq-874270dd4ea2','mcq','en','Who founded the modern Kingdom of Saudi Arabia in 1932?','0','["King Abdulaziz Al Saud","King Saud","King Faisal","Imam Muhammad ibn Saud"]','[]','',1),
('mcq-75738354af27','mcq','en','What is the capital of Saudi Arabia?','0','["Riyadh","Jeddah","Dammam","Abha"]','[]','',1),
('mcq-d9c09b72a1ce','mcq','ar','ما هي أكبر قارة من حيث المساحة؟','0','["آسيا","أفريقيا","أوروبا","أمريكا الجنوبية"]','[]','',1),
('mcq-49460a37ba94','mcq','en','Which is typically a fixed cost?','0','["Rent","Raw materials","Shipping per order","Sales commission"]','[]','',1),
('mcq-8650074f57b5','mcq','ar','ما هو أكبر كوكب في المجموعة الشمسية؟','0','["المشتري","زحل","أورانوس","نبتون"]','[]','',1),
('mcq-abdaaf6b053f','mcq','en','How many bones are in the adult human body?','0','["206","210","201","198"]','[]','',1),
('mcq-cdc15276a0f1','mcq','en','Who developed the concept of algorithms?','1','["Euclid","Al-Khwarizmi","Pythagoras","Archimedes"]','[]','Al-Khwarizmi''s name gave us the word ''algorithm''.',1),
('mcq-6bcd1efde970','mcq','en','What did Plato''s ''Allegory of the Cave'' illustrate?','1','["The nature of justice","The limits of perception","The ideal state","The immortality of the soul"]','[]','The allegory illustrates how our perception can limit our understanding of reality.',1),
('mcq-3c1d1ae239b0','mcq','en','Who is considered the father of Western philosophy?','1','["Plato","Socrates","Aristotle","Pythagoras"]','[]','Socrates is widely credited as the founder of Western philosophy.',1),
('mcq-736a455cad14','mcq','en','What is the concept of ''waḥdat al-wujūd''?','1','["Divine unity","Unity of existence","Monotheism","Cosmic harmony"]','[]','Waḥdat al-wujūd is Ibn Arabi''s concept of the unity of all existence.',1),
('mcq-88cdf89690b0','mcq','ar','ما معنى كلمة ''فلسفة''؟','0','["حب الحكمة","البحث عن الحقيقة","علم المنطق","فن التفكير"]','[]','كلمة فلسفة مشتقة من اليونانية وتعني ''حب الحكمة''.',1),
('mcq-0292e8603a11','mcq','ar','من كتب ''ألف ليلة وليلة''؟','0','["مؤلف مجهول","الجاحظ","المتنبي","أبو العلاء المعري"]','[]','ألف ليلة وليلة هي مجموعة قصص شعبية لا يُعرف مؤلفها الأصلي.',1),
('mcq-601cc8355c1b','mcq','en','Who wrote ''The Prophet''?','1','["Rumi","Kahlil Gibran","Omar Khayyam","Ibn Arabi"]','[]','Kahlil Gibran wrote ''The Prophet'' in 1923.',1),
('mcq-64ae8ed1ebb2','mcq','en','What was the ''House of Wisdom''?','1','["A mosque","A library and translation center","A palace","A university"]','[]','The House of Wisdom was a major intellectual center for translation and scholarship in Baghdad.',1),
('mcq-49bbddbd9cfd','mcq','ar','ما هو موضوع كتاب ''تهافت الفلاسفة''؟','0','["نقد الفلسفة اليونانية","الدفاع عن التصوف","شرح المنطق","تاريخ الفلسفة"]','[]','انتقد الغزالي في هذا الكتاب تأثير الفلسفة اليونانية على الفكر الإسلامي.',1),
('mcq-0438ef926333','mcq','en','What is Al-Ghazali''s ''Incoherence of the Philosophers'' a critique of?','1','["Islamic theology","Greek philosophy in Islam","Sufism","Political philosophy"]','[]','Al-Ghazali critiqued the influence of Greek philosophy on Islamic thought.',1),
('mcq-850de0203911','mcq','en','What is the meaning of ''logos'' in Greek philosophy?','1','["Love","Reason/Word","Soul","Nature"]','[]','Logos refers to reason, word, or the principle of order and knowledge.',1),
('mcq-9b58084c10ff','mcq','en','What is the Socratic method primarily based on?','1','["Lecturing","Questioning","Meditation","Writing"]','[]','The Socratic method uses questioning to stimulate critical thinking.',1),
('mcq-4ecee33d7b23','mcq','en','Who wrote the ''Rubaiyat''?','2','["Hafez","Rumi","Omar Khayyam","Saadi"]','[]','The Rubaiyat was written by the Persian poet Omar Khayyam.',1),
('mcq-9bfe779c5504','mcq','ar','أين تأسس بيت الحكمة؟','2','["القاهرة","دمشق","بغداد","قرطبة"]','[]','تأسس بيت الحكمة في بغداد خلال العصر العباسي.',1),
('mcq-a25a95ea3c88','mcq','en','What is the ''Muqaddimah''?','1','["A book of poetry","An introduction to history","A religious text","A medical encyclopedia"]','[]','Ibn Khaldun''s Muqaddimah is a groundbreaking introduction to the study of history.',1),
('mcq-a28a4ad5e204','mcq','en','In which century did the Islamic Golden Age begin?','1','["6th century","8th century","10th century","12th century"]','[]','The Islamic Golden Age began in the 8th century during the Abbasid Caliphate.',1),
('mcq-cf9f3c085005','mcq','en','What branch of philosophy deals with morality?','2','["Logic","Metaphysics","Ethics","Aesthetics"]','[]','Ethics is the study of moral principles and values.',1),
('mcq-5b68d0baede8','mcq','en','What does ''cogito ergo sum'' mean?','1','["Knowledge is power","I think, therefore I am","The truth will set you free","Know thyself"]','[]','Descartes'' famous phrase means ''I think, therefore I am''.',1),
('mcq-86736132e165','mcq','en','What is the main focus of epistemology?','1','["Ethics","Knowledge","Existence","Beauty"]','[]','Epistemology is the branch of philosophy concerned with knowledge.',1),
('mcq-22adf9fe41c0','mcq','ar','من هو مؤسس علم الاجتماع؟','1','["الفارابي","ابن خلدون","ابن سينا","الغزالي"]','[]','يعتبر ابن خلدون مؤسس علم الاجتماع الحديث.',1),
('mcq-4082b409fef0','mcq','en','What literary form is Rumi most famous for?','1','["Epic poetry","Mystical poetry","Satire","Drama"]','[]','Rumi is celebrated for his mystical Sufi poetry.',1),
('mcq-16cc79df2f1a','mcq','ar','ما هو المبدأ الأساسي في فلسفة الفارابي؟','0','["المدينة الفاضلة","وحدة الوجود","الشك المنهجي","العقل العملي"]','[]','اشتهر الفارابي بنظريته عن المدينة الفاضلة.',1),
('mcq-91423f424465','mcq','ar','في أي قرن بدأ العصر الذهبي الإسلامي؟','1','["القرن السادس","القرن الثامن","القرن العاشر","القرن الثاني عشر"]','[]','بدأ العصر الذهبي الإسلامي في القرن الثامن الميلادي.',1),
('mcq-a4c7901a028e','mcq','en','Who is known as the ''Father of Medicine''?','1','["Galen","Hippocrates","Ibn Sina","Paracelsus"]','[]','Hippocrates is traditionally regarded as the father of medicine.',1),
('mcq-f0cd031dae09','mcq','en','What does ''Hikmah'' mean in Arabic?','1','["Knowledge","Wisdom","Truth","Justice"]','[]','Hikmah (حكمة) means wisdom in Arabic.',1),
('mcq-6973b47918ec','mcq','en','Which city was the center of learning during the Islamic Golden Age?','2','["Cairo","Damascus","Baghdad","Cordoba"]','[]','Baghdad and its House of Wisdom were the intellectual center of the Islamic world.',1),
('mcq-cdc50d26306b','mcq','en','Who discovered pulmonary circulation?','2','["Galen","Harvey","Ibn al-Nafis","Vesalius"]','[]','Ibn al-Nafis described pulmonary circulation centuries before Harvey.',1)
on conflict (id) do nothing;
