-- Hikmah content import, 21 Sep 2026
-- Source: Areej's earlier puzzle tables (puzzles, cryptograms). 597 rows: 553 letters, 44 cryptograms.
-- Already applied to production project vilgghdzyqdsvbaazphh. Idempotent: safe to run again on a rebuilt database.
-- Data only. No schema change. lib/game/seed.json and the local tests are untouched and still expect 80 seed puzzles.
-- Roll back without deleting history:
--   update hikmah.content set active=0 where id ~ '^(letters|cryptogram)-[0-9a-f]{12}$';

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-8a470469a94d','letters','ar','لا يجتمع حب وحقد في قلب واحد','قلب','[]','[]','',1),
('letters-6fb7252dc0dd','letters','en','A workman is known by his tools.','tools','[]','[]','',1),
('letters-31fd433aeac6','letters','en','Contentment is a constant feast.','feast','[]','[]','',1),
('letters-f9b02811883e','letters','ar','جودة القهوة من جودة الماء.','الماء','[]','[]','',1),
('letters-ff7d7cfd7360','letters','ar','الرجوع إلى الحق فضيلة','فضيلة','[]','[]','',1),
('letters-23cd0b8fe050','letters','en','The pen is mightier than the sword.','pen','[]','[]','',1),
('letters-fe7f2df2e902','letters','en','He who wants to eat the nut must crack the shell (German).','shell','[]','[]','',1),
('letters-633067dc2847','letters','ar','التكبر على المتكبر تواضع','المتكبر','[]','[]','',1),
('letters-ae306a8064bb','letters','en','The truth is often unpalatable.','unpalatable','[]','[]','',1),
('letters-13b0c0e0921f','letters','en','Haste makes waste.','waste','[]','[]','',1),
('letters-fe54cdeec31f','letters','en','Great oaks from little acorns grow.','acorns','[]','[]','',1),
('letters-56361dec35eb','letters','en','A smooth sea never made a skilled sailor.','skilled','[]','[]','',1),
('letters-ed254c238431','letters','ar','سقوط الورقة رسالة للعالم.','الورقة','[]','[]','',1),
('letters-628a118c42fe','letters','ar','البحر الهادئ لا يصنع بحّارًا ماهرًا.','ماهرًا','[]','[]','',1),
('letters-0b04c4e84590','letters','ar','حيثما ذهبت فاذهب بكل قلبك.','قلبك','[]','[]','',1),
('letters-f3241ebe854f','letters','ar','لا تبحر أبعد مما تستطيع العودة منه.','العودة','[]','[]','',1),
('letters-617b8b88255c','letters','en','The chickens have come home to roost.','roost','[]','[]','',1),
('letters-1921a7c19fa7','letters','ar','من هان عليه ماله فقد كرمت عليه نفسه.','ماله','[]','[]','',1),
('letters-481c33dde83d','letters','en','Out of the frying pan and into the fire.','frying','[]','[]','',1),
('letters-8b1844792180','letters','ar','السكوت من ذهب.','ذهب','[]','[]','',1),
('letters-c82410cc03c6','letters','en','If the cap fits, wear it.','fits','[]','[]','',1),
('letters-6ba1839f0ceb','letters','ar','دوام الحال من المحال','المحال','[]','[]','',1),
('letters-a1723ef24707','letters','ar','العلم تاج على رأس صاحبه','تاج','[]','[]','',1),
('letters-42dc0d2765a6','letters','ar','الحظ يساند العقل المستعد.','المستعد','[]','[]','',1),
('letters-b517b24bc507','letters','en','You reap what you sow.','reap','[]','[]','',1),
('letters-d061ae0964b3','letters','ar','الحياة جسر فاعبره ولا تبنِ عليه بيتًا.','جسر','[]','[]','',1),
('letters-ac2e5ba5ad3f','letters','en','Don''t let the sun go down on your anger.','anger','[]','[]','',1),
('letters-16921a600eff','letters','ar','الأغنى من قنع بالقليل.','القليل','[]','[]','',1),
('letters-4cc6af56e96f','letters','en','The greatest wealth is a poverty of desires.','desires','[]','[]','',1),
('letters-3d7a5771ea4c','letters','en','He who is born to be hanged shall never be drowned.','drowned','[]','[]','',1),
('letters-482673522c68','letters','en','Still waters run deep.','deep','[]','[]','',1),
('letters-10b77ea070ba','letters','ar','إذا دخل الفقر من الباب خرج الحب من النافذة','الفقر','[]','[]','',1),
('letters-beac13893807','letters','en','The shrimp that falls asleep is carried away by the current (Spanish).','shrimp','[]','[]','',1),
('letters-c24fd9a06278','letters','ar','إذا تم العقل نقص الكلام','العقل','[]','[]','',1),
('letters-cbaaf1b67c08','letters','ar','عِظَم الشك يولّد عِظَم الحكمة، وصِغَر الشك يولّد قِلّتها.','الحكمة','[]','[]','',1),
('letters-2539b2f564d6','letters','en','A clever person solves a problem. A wise person avoids it (Jewish).','avoids','[]','[]','',1),
('letters-f84bebabb522','letters','ar','كل لبيب بالإشارة يفهم.','لبيب','[]','[]','',1),
('letters-6199e5142352','letters','en','Never test the depth of the water with both feet.','depth','[]','[]','',1),
('letters-90411d1cf589','letters','en','Words are like arrows; once shot, they cannot be recalled.','recalled','[]','[]','',1),
('letters-131d39b1c6e4','letters','ar','لا تُستخدم المدافع لقتل الذباب.','الذباب','[]','[]','',1),
('letters-1bcc337db031','letters','ar','ما يفكر به القلب ينطق به اللسان.','اللسان','[]','[]','',1),
('letters-926f41ea876d','letters','ar','من لا يعرفك يجهلك','يعرفك','[]','[]','',1),
('letters-524e6e13dc79','letters','en','Speech is silver, silence is gold.','speech','[]','[]','',1),
('letters-3c9ff1f39bab','letters','en','Birds of a feather flock together.','feather','[]','[]','',1),
('letters-f30341b3254b','letters','ar','من يرمي الشمس بالحجارة لا يصيب إلا نفسه.','نفسه','[]','[]','',1),
('letters-b941ba84e84b','letters','en','He who buys what he does not need steals from himself.','need','[]','[]','',1),
('letters-f0a94ead38ee','letters','en','A fool and his money are soon parted.','parted','[]','[]','',1),
('letters-f181febf0242','letters','ar','بيدي لا بيد عمرو.','بيدي','[]','[]','',1),
('letters-8e7913040bba','letters','ar','أدب المرء خير من ذهبه.','أدب','[]','[]','',1),
('letters-9ba794176054','letters','en','Many hands make light work.','hands','[]','[]','',1),
('letters-99427bbf26c7','letters','ar','افصل ثوبك على قدر قماشك.','قماشك','[]','[]','',1),
('letters-561cee60ce94','letters','en','The early bird catches the worm.','early','[]','[]','',1),
('letters-ff63873ec513','letters','ar','أصعب خطوة هي الأولى عبر الباب.','الأولى','[]','[]','',1),
('letters-0b4ad69732e6','letters','ar','لا يُستخرج الدم من الحجر.','الحجر','[]','[]','',1),
('letters-458fc905ba49','letters','en','Happiness is not a destination, but a method of travel.','method','[]','[]','',1),
('letters-bea8805fe965','letters','ar','بقدر الكد تكتسب المعالي.','الكد','[]','[]','',1),
('letters-5508747e7036','letters','ar','الباب المغلق لا يمنع إلا الصادقين.','المغلق','[]','[]','',1),
('letters-7ee891f92d4d','letters','ar','لكل جواد كبوة','كبوة','[]','[]','',1),
('letters-8dad78dd9e5f','letters','ar','الصمت سياج الحكمة.','الصمت','[]','[]','',1),
('letters-99dec887d558','letters','en','Turn your face to the sun and the shadows fall behind you (Maori).','shadows','[]','[]','',1),
('letters-4fe85061b6cb','letters','ar','النخلة تنمو أفضل تحت الحمل.','الحمل','[]','[]','',1),
('letters-613dada956bd','letters','en','Experience is the teacher of all things.','teacher','[]','[]','',1),
('letters-fec46863a657','letters','en','Don''t burn your bridges behind you.','bridges','[]','[]','',1),
('letters-288c98109f07','letters','en','A stitch in time saves nine.','stitch','[]','[]','',1),
('letters-ed55f2a6fc95','letters','en','Even the sun has spots.','spots','[]','[]','',1),
('letters-d0129efd2eb6','letters','ar','من كثر كلامه كثر سقطه.','كلامه','[]','[]','',1),
('letters-1236a26c26fc','letters','en','Fortune favors the prepared mind.','prepared','[]','[]','',1),
('letters-78cb45a5a6a3','letters','ar','أحبب حبيبك هوناً ما.','هوناً','[]','[]','',1),
('letters-b04e61c64055','letters','en','Rome wasn''t built in a day.','day','[]','[]','',1),
('letters-fa49fae2df01','letters','en','Health is wealth.','health','[]','[]','',1),
('letters-bcdded2db6fa','letters','en','He who digs a pit for others falls into it himself.','pit','[]','[]','',1),
('letters-8adafac7bcfe','letters','en','Don''t cross the bridge until you come to it.','bridge','[]','[]','',1),
('letters-6f0c47676667','letters','en','To improve is to change; to be perfect is to change often.','improve','[]','[]','',1),
('letters-ef8555bca3ec','letters','ar','عند الامتحان يُكرم المرء أو يُهان','الامتحان','[]','[]','',1),
('letters-2f42cd14ae92','letters','en','The bridge is repaired before the flood (Chinese).','flood','[]','[]','',1),
('letters-6eaa717e584e','letters','en','A bird does not sing because it has an answer, it sings because it has a song (Chinese).','sings','[]','[]','',1),
('letters-f87c6b08ef19','letters','en','As you make your bed, so you must lie in it.','bed','[]','[]','',1),
('letters-d93dfc31a991','letters','en','The more things change, the more they stay the same.','change','[]','[]','',1),
('letters-1d456b69ea54','letters','en','The higher they climb, the harder they fall.','climb','[]','[]','',1),
('letters-884d90b61cdb','letters','en','Blood is thicker than water.','thicker','[]','[]','',1),
('letters-32b2e67e2915','letters','en','Many kiss the hand they wish to cut off.','kiss','[]','[]','',1),
('letters-5f8c8a04e91d','letters','ar','قليل دائم خير من كثير منقطع.','دائم','[]','[]','',1),
('letters-56c1e35a7516','letters','ar','بشر القاتل بالقتل ولو بعد حين.','حين','[]','[]','',1),
('letters-6e0a52557727','letters','en','Not all who wander are lost.','wander','[]','[]','',1),
('letters-5ac07d6dcc0f','letters','ar','القناعة كنز لا يفنى.','القناعة','[]','[]','',1),
('letters-879f52e9f158','letters','en','The heart wants what it wants.','heart','[]','[]','',1),
('letters-f4e759f59f4e','letters','en','Better to be a beggar and alive than an emperor and dead.','alive','[]','[]','',1),
('letters-4122f504a7bb','letters','en','Don''t throw good money after bad.','money','[]','[]','',1),
('letters-265901538ff6','letters','ar','العظائم لا تُنجز بدفعة واحدة بل بتراكم الصغائر.','تراكم','[]','[]','',1),
('letters-30fcf2e388bc','letters','en','A rolling stone gathers no moss.','moss','[]','[]','',1),
('letters-f7871b37e87b','letters','en','One generation plants the trees, another gets the shade.','shade','[]','[]','',1),
('letters-1ebfd65de27b','letters','ar','سوء الحظ يأتي ثلاثيًا.','ثلاثيًا','[]','[]','',1),
('letters-c24961e4fda9','letters','en','Small favors make a great debt.','debt','[]','[]','',1),
('letters-ee3f8542ea3d','letters','en','Attack is the best defense.','defense','[]','[]','',1),
('letters-3aec891c7985','letters','en','The grass is always greener on the other side.','greener','[]','[]','',1),
('letters-c56ec4b230af','letters','en','No man can serve two masters.','masters','[]','[]','',1),
('letters-fe985bc3a637','letters','en','The wind does not break a tree that can bend.','bend','[]','[]','',1),
('letters-978c045d8d16','letters','en','Expect the unexpected.','unexpected','[]','[]','',1),
('letters-e9b90883e7de','letters','ar','لا تمدح غائباً حتى يأتيك.','غائباً','[]','[]','',1),
('letters-e47a40a0b63e','letters','en','A closed mouth catches no flies.','mouth','[]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-9ad377b3abaa','letters','en','Time and tide wait for no man.','tide','[]','[]','',1),
('letters-989223168047','letters','en','Luxury is a burden; simplicity is a gift.','simplicity','[]','[]','',1),
('letters-71fdbe2f30a3','letters','en','Hope for the best, but prepare for the worst.','prepare','[]','[]','',1),
('letters-850fa54a1ec4','letters','en','When the house is on fire, you don''t need a flute.','flute','[]','[]','',1),
('letters-46c274589329','letters','en','Two wrongs don''t make a right.','right','[]','[]','',1),
('letters-db6d2493de2b','letters','en','Discretion is the better part of valor.','discretion','[]','[]','',1),
('letters-f1d21492590b','letters','en','Walls have ears.','ears','[]','[]','',1),
('letters-1f3dd121fc43','letters','en','Genius is one percent inspiration and ninety-nine percent perspiration.','perspiration','[]','[]','',1),
('letters-0fc512766b7d','letters','ar','من حفر حفرة لأخيه وقع فيها.','حفرة','[]','[]','',1),
('letters-f6553e3e14b5','letters','ar','اختلط الحابل بالنابل.','الحابل','[]','[]','',1),
('letters-00971c27539d','letters','en','It is better to wear out than to rust out.','rust','[]','[]','',1),
('letters-dd7e3b725d03','letters','ar','الحاجة أم الاختراع','الاختراع','[]','[]','',1),
('letters-8c086894a647','letters','en','Forewarned is forearmed.','forewarned','[]','[]','',1),
('letters-a5206e82ecc5','letters','en','The hardest step is always the first one through the door.','hardest','[]','[]','',1),
('letters-b0fb4022b9c1','letters','en','What the heart thinks, the mouth speaks.','mouth','[]','[]','',1),
('letters-38eeba8b699d','letters','en','Two heads are better than one.','heads','[]','[]','',1),
('letters-0f8ae9a1d088','letters','ar','الصغير من المعروف يصنع دينًا كبيرًا.','دينًا','[]','[]','',1),
('letters-3239a1521289','letters','en','Listen twice as much as you speak.','listen','[]','[]','',1),
('letters-22d97c25109f','letters','en','Count your blessings.','blessings','[]','[]','',1),
('letters-6b30f6a37e6f','letters','ar','الطمع يقل ما جمع','الطمع','[]','[]','',1),
('letters-d809c61abc1d','letters','en','The earth produces all things and receives all things.','earth','[]','[]','',1),
('letters-f1bd1215903f','letters','ar','الوحدة خير من جليس السوء.','السوء','[]','[]','',1),
('letters-80a076d8c806','letters','en','The highest branch is not always the safest.','safest','[]','[]','',1),
('letters-353f80a719b6','letters','en','Comparison is the thief of joy.','thief','[]','[]','',1),
('letters-4998ba256359','letters','ar','من راقب الناس مات همًّا','راقب','[]','[]','',1),
('letters-701353488172','letters','en','Absence makes the heart grow fonder.','fonder','[]','[]','',1),
('letters-617579a1c880','letters','en','A heavy purse makes a light heart.','purse','[]','[]','',1),
('letters-346c09bb0217','letters','ar','لا دخان بلا نار','نار','[]','[]','',1),
('letters-767741a7603a','letters','en','If you want to go fast, go alone. If you want to go far, go together (African).','together','[]','[]','',1),
('letters-915b4b7bedda','letters','en','Life is what happens while you''re making other plans.','plans','[]','[]','',1),
('letters-cef75b48fa16','letters','en','You cannot hide the sun with one hand (Arabic).','sun','[]','[]','',1),
('letters-1b039c564d7f','letters','ar','ما طار طير وارتفع إلا كما طار وقع.','طير','[]','[]','',1),
('letters-89b57e7ec29c','letters','en','Barking dogs seldom bite.','barking','[]','[]','',1),
('letters-c51a3ac27e68','letters','en','Deep rivers move with silent majesty; shallow brooks are noisy.','majesty','[]','[]','',1),
('letters-5a6ae7141b75','letters','ar','الغاية تبرر الوسيلة.','الوسيلة','[]','[]','',1),
('letters-1ed8aef1137e','letters','en','A person who chases two rabbits catches neither.','neither','[]','[]','',1),
('letters-35cb9f84b3e8','letters','ar','إن البعوضة تدمي مقلة الأسد','البعوضة','[]','[]','',1),
('letters-26fee3ac4dee','letters','en','A wise man changes his mind, a fool never will.','changes','[]','[]','',1),
('letters-5261809e42e3','letters','en','Ignorance is bliss.','bliss','[]','[]','',1),
('letters-940ef13c1b8a','letters','en','The end justifies the means.','means','[]','[]','',1),
('letters-218969fdd0a0','letters','en','Aim for the moon; even if you miss, you''ll land among the stars.','stars','[]','[]','',1),
('letters-099094056c58','letters','ar','لا يُجمع سيفان في غمد واحد','غمد','[]','[]','',1),
('letters-12b608f87e29','letters','en','You can''t whistle and chew meal at the same time.','whistle','[]','[]','',1),
('letters-eccabe7c35e7','letters','ar','صديق قديم خير من صديقين جديدين.','قديم','[]','[]','',1),
('letters-2796f66cb7ae','letters','en','All things are difficult before they are easy.','difficult','[]','[]','',1),
('letters-b5edfa22d753','letters','en','Dead men tell no tales.','tales','[]','[]','',1),
('letters-07df6faf1ea3','letters','ar','ثقب صغير يُغرق سفينة عظيمة.','سفينة','[]','[]','',1),
('letters-72c6957a985e','letters','en','Like father, like son.','father','[]','[]','',1),
('letters-10fd36ac2a80','letters','ar','عين الصديق مرآة صادقة.','مرآة','[]','[]','',1),
('letters-74bc9b2474ba','letters','en','Don''t look a gift horse in the mouth.','horse','[]','[]','',1),
('letters-57093ad64f46','letters','ar','السعادة ليست وجهة بل أسلوب سفر.','أسلوب','[]','[]','',1),
('letters-efc1466f5a82','letters','en','People who live in glass houses shouldn''t throw stones.','stones','[]','[]','',1),
('letters-5b19d9786faf','letters','ar','غدًا أكثر أيام الأسبوع انشغالًا.','غدًا','[]','[]','',1),
('letters-c58644eb8742','letters','ar','القناعة وليمة دائمة.','القناعة','[]','[]','',1),
('letters-c118b9819b84','letters','en','Everything comes to him who waits.','waits','[]','[]','',1),
('letters-876f919bf708','letters','ar','السعيد من يبني أساسه بحجارة رماه بها الآخرون.','أساسه','[]','[]','',1),
('letters-16cc5035875c','letters','en','If you want to jump high, you must bend your knees.','knees','[]','[]','',1),
('letters-a9f28f4f5a7f','letters','en','Beauty is in the eye of the beholder.','beholder','[]','[]','',1),
('letters-f51ceea0fc55','letters','ar','كثرة العتاب تفسد الصداقة.','العتاب','[]','[]','',1),
('letters-fbeaea8d4169','letters','ar','حتى الشمس لها بقع.','بقع','[]','[]','',1),
('letters-2aa349773dee','letters','en','Practice what you preach.','preach','[]','[]','',1),
('letters-22c726589f3e','letters','en','You can''t teach an old dog new tricks.','tricks','[]','[]','',1),
('letters-ac2f0eea4615','letters','ar','الحظ يطرق باب كل إنسان مرة واحدة على الأقل.','الحظ','[]','[]','',1),
('letters-49e954ecc6da','letters','en','There is a black sheep in every flock.','sheep','[]','[]','',1),
('letters-40e6b9da06a4','letters','en','Only a fool tests the water with both feet (African).','fool','[]','[]','',1),
('letters-4f54cd94faa9','letters','en','Great things are not done by impulse, but by a series of small things brought together.','series','[]','[]','',1),
('letters-763844f94fae','letters','en','The palm tree grows best under weight.','weight','[]','[]','',1),
('letters-2abb967b750c','letters','ar','إذا فات الفوت ما ينفع الصوت','الصوت','[]','[]','',1),
('letters-9ae49b13c98f','letters','en','A man with one watch knows what time it is; a man with two is never sure.','watch','[]','[]','',1),
('letters-ef80d71c45f4','letters','en','A man''s house is his castle.','castle','[]','[]','',1),
('letters-a06e11830583','letters','ar','يوم العدل على الظالم أشد من يوم الجور على المظلوم.','العدل','[]','[]','',1),
('letters-816f6dd90f6a','letters','ar','العين بصيرة واليد قصيرة.','قصيرة','[]','[]','',1),
('letters-385119711161','letters','ar','اللسان أداة تزداد حدّة بالاستخدام.','اللسان','[]','[]','',1),
('letters-298244b33f78','letters','ar','أن تبلى خير من أن تصدأ.','تصدأ','[]','[]','',1),
('letters-219937d51bf6','letters','ar','لكل مقام مقال','مقال','[]','[]','',1),
('letters-b4b4e42942b1','letters','en','He who has no house is a neighbor to everyone.','neighbor','[]','[]','',1),
('letters-03a68ebcf4d4','letters','en','Beauty is only skin deep.','beauty','[]','[]','',1),
('letters-771d91af25ff','letters','ar','أقرض فقط ما تستطيع خسارته.','خسارته','[]','[]','',1),
('letters-f2445e23c65e','letters','en','He who sleeps with dogs rises with fleas.','fleas','[]','[]','',1),
('letters-94fd63b48bc7','letters','en','Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.','lifetime','[]','[]','',1),
('letters-455dbb7e1d92','letters','ar','الطبيعة لا تفعل شيئًا عبثًا.','عبثًا','[]','[]','',1),
('letters-601c34c1aa5e','letters','en','Tell me who your friends are, and I''ll tell you who you are.','friends','[]','[]','',1),
('letters-98c8cc9886e0','letters','ar','الطيور على أشكالها تقع.','أشكالها','[]','[]','',1),
('letters-bb74d19a1c0b','letters','en','You can''t have your cake and eat it too.','cake','[]','[]','',1),
('letters-f2e01d3ba07a','letters','ar','جيش من الخراف يقوده أسد خير من جيش من الأسود يقوده خروف.','خروف','[]','[]','',1),
('letters-85908253c4f3','letters','en','A new broom sweeps clean.','broom','[]','[]','',1),
('letters-16e72d377692','letters','en','He is richest who is content with the least.','least','[]','[]','',1),
('letters-971426425c19','letters','ar','خير جليس في الزمان كتاب','كتاب','[]','[]','',1),
('letters-b9840a969d17','letters','en','A sound mind in a sound body.','mind','[]','[]','',1),
('letters-e5f1df3a0662','letters','ar','الكذب داء والصدق دواء','الصدق','[]','[]','',1),
('letters-56b54e3fb38b','letters','en','Don''t let your left hand know what your right hand is doing.','left','[]','[]','',1),
('letters-f05ea3d68c03','letters','ar','من استعجل الشيء قبل أوانه عوقب بحرمانه','أوانه','[]','[]','',1),
('letters-788fc3224a8a','letters','en','Business before pleasure.','business','[]','[]','',1),
('letters-4e188b3ffd83','letters','ar','الضمير الصافي وسادة ناعمة.','الضمير','[]','[]','',1),
('letters-b89bb22f1632','letters','en','The best is the enemy of the good.','enemy','[]','[]','',1),
('letters-f52a3694b806','letters','en','Money can''t buy happiness.','happiness','[]','[]','',1),
('letters-a86ed00440bf','letters','en','Better an hour too soon than a minute too late.','minute','[]','[]','',1),
('letters-9ce7c6723f78','letters','ar','الدهر يومان يوم لك ويوم عليك.','يومان','[]','[]','',1),
('letters-5e7392d66dcb','letters','en','What cures Sancho makes Martha sick.','sancho','[]','[]','',1),
('letters-fab59d8de2bf','letters','en','Death is the great leveler.','leveler','[]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-0bd37750c8b9','letters','ar','العفو عند المقدرة.','المقدرة','[]','[]','',1),
('letters-ced8c547f42a','letters','en','Half the truth is often a whole lie.','lie','[]','[]','',1),
('letters-c7355b84f999','letters','en','Home is where the heart is.','heart','[]','[]','',1),
('letters-2553f9709e2b','letters','en','Many a true word is spoken in jest.','jest','[]','[]','',1),
('letters-772baac5e612','letters','en','Don''t kill the goose that lays the golden eggs.','goose','[]','[]','',1),
('letters-e24e92d498a2','letters','en','Wherever you go, go with all your heart (Confucian).','heart','[]','[]','',1),
('letters-e180bad97b8b','letters','ar','الريح لا تكسر الشجرة التي تنحني.','تنحني','[]','[]','',1),
('letters-18a31861e6be','letters','en','He who plays with fire gets burned.','fire','[]','[]','',1),
('letters-11d519253443','letters','en','Laughter is the best medicine.','laughter','[]','[]','',1),
('letters-b40388357c97','letters','en','Early to bed and early to rise makes a man healthy, wealthy, and wise.','rise','[]','[]','',1),
('letters-529aea8363a4','letters','en','A happy heart makes a blooming visage.','visage','[]','[]','',1),
('letters-d7c8fb0814d9','letters','ar','الجود من الموجود.','الموجود','[]','[]','',1),
('letters-192132873b4e','letters','ar','الناس أعداء ما جهلوا','جهلوا','[]','[]','',1),
('letters-cd2b85071136','letters','en','Cleanliness is next to godliness.','cleanliness','[]','[]','',1),
('letters-ba4d1c2a5b2d','letters','en','Diligence is the mother of good luck.','diligence','[]','[]','',1),
('letters-72e495619f05','letters','ar','رحم الله امرءًا عرف قدر نفسه','قدر','[]','[]','',1),
('letters-75bdf699e9c8','letters','en','Poverty is the mother of all arts.','poverty','[]','[]','',1),
('letters-c53728a1c5ad','letters','en','A guilty conscience needs no accuser.','conscience','[]','[]','',1),
('letters-a840aed16dcb','letters','ar','فاقد الشيء لا يعطيه','فاقد','[]','[]','',1),
('letters-a9be4270cc16','letters','en','Riches serve a wise man but command a fool.','riches','[]','[]','',1),
('letters-2614cc0180fb','letters','en','Patience is a bitter plant, but it has sweet fruit.','patience','[]','[]','',1),
('letters-71ed4818d069','letters','en','A fish stinks from the head down.','fish','[]','[]','',1),
('letters-db042e72fc01','letters','ar','لا تؤجل عمل اليوم إلى الغد.','اليوم','[]','[]','',1),
('letters-5465577e5b2c','letters','en','If you want to be happy for a lifetime, help someone else.','lifetime','[]','[]','',1),
('letters-a3b8fb4bd940','letters','ar','قبضة هادئة خير من يدين ممتلئتين بالتعب.','هادئة','[]','[]','',1),
('letters-717e28448df5','letters','en','Think before you speak.','think','[]','[]','',1),
('letters-526ec8dea2f7','letters','ar','من طلب العلا سهر الليالي.','العلا','[]','[]','',1),
('letters-252bdb314175','letters','ar','العقل زينة.','زينة','[]','[]','',1),
('letters-63e0bc5022a7','letters','en','You are what you eat.','eat','[]','[]','',1),
('letters-ce5f906cf6df','letters','en','There is no time like the present.','present','[]','[]','',1),
('letters-ad76001e833b','letters','ar','ما كل ما يلمع ذهبًا','ذهبًا','[]','[]','',1),
('letters-746a57cea3be','letters','ar','الصدق منجاة.','منجاة','[]','[]','',1),
('letters-5beaadeecb3c','letters','en','Fair words butter no parsnips.','parsnips','[]','[]','',1),
('letters-7a06aaaf7ffe','letters','ar','لا يُفتى ومالك في المدينة','المدينة','[]','[]','',1),
('letters-5c505515f4c6','letters','ar','ألف احتمال لا يصنع حقيقة واحدة.','حقيقة','[]','[]','',1),
('letters-13742c71fd2e','letters','en','Better a handful with quietness than both hands full with toil.','quietness','[]','[]','',1),
('letters-be6d485a720a','letters','en','A small house can hold a hundred friends.','hundred','[]','[]','',1),
('letters-fb19c77c7ced','letters','ar','الطبع يغلب التطبع.','الطبع','[]','[]','',1),
('letters-88a0af30fc45','letters','en','Man proposes, God disposes.','disposes','[]','[]','',1),
('letters-2437ce5c9f68','letters','en','The way to a man''s heart is through his stomach.','stomach','[]','[]','',1),
('letters-4d63dbe5dd63','letters','en','No use crying over spilled milk.','milk','[]','[]','',1),
('letters-089a3193a4ac','letters','en','What doesn''t kill you makes you stronger.','stronger','[]','[]','',1),
('letters-02f3b3eb34b6','letters','en','Keep your friends close and your enemies closer.','enemies','[]','[]','',1),
('letters-89393879a461','letters','en','Live and let live.','let','[]','[]','',1),
('letters-d0478d78c590','letters','ar','البعد جفاء.','جفاء','[]','[]','',1),
('letters-d4ee8bc230d4','letters','ar','من قنع كفاه.','قنع','[]','[]','',1),
('letters-37cb9c653103','letters','en','Your ears will not lead you into trouble, but your tongue will.','ears','[]','[]','',1),
('letters-a2716e975340','letters','en','Success has many fathers, but failure is an orphan.','orphan','[]','[]','',1),
('letters-f38c77adec12','letters','en','A friend''s eye is a good mirror.','mirror','[]','[]','',1),
('letters-21971c7eea93','letters','en','It''s always darkest before the dawn.','darkest','[]','[]','',1),
('letters-1553f54bac0f','letters','en','You cannot wash blood with blood (Persian).','wash','[]','[]','',1),
('letters-3261a271fc11','letters','ar','عامل الناس كما تحب أن يعاملوك','يعاملوك','[]','[]','',1),
('letters-de5261677725','letters','en','The apple doesn''t fall far from the tree.','apple','[]','[]','',1),
('letters-b272c73a60d2','letters','en','Great minds think alike.','minds','[]','[]','',1),
('letters-b141d671810c','letters','en','Luck is what happens when preparation meets opportunity.','preparation','[]','[]','',1),
('letters-34a454846baf','letters','ar','الباب الذي يأتيك منه الريح سده واستريح.','الريح','[]','[]','',1),
('letters-9eebaf84100d','letters','en','The tongue is the only tool that grows sharper with use.','tongue','[]','[]','',1),
('letters-54a17275f9bb','letters','en','Necessity knows no law.','law','[]','[]','',1),
('letters-21e286233ad2','letters','en','The cobbler should stick to his last.','cobbler','[]','[]','',1),
('letters-c535491495f4','letters','ar','كثيرًا ما تُقال الحقيقة مزاحًا.','الحقيقة','[]','[]','',1),
('letters-7d933cc51c0c','letters','en','Love your neighbor, but don''t pull down your hedge.','hedge','[]','[]','',1),
('letters-9195bb010661','letters','en','A word to the wise is sufficient.','sufficient','[]','[]','',1),
('letters-80179d57e52a','letters','en','Tough times never last, but tough people do.','last','[]','[]','',1),
('letters-2b5c7ba3b367','letters','ar','لسانك حصانك إن صنته صانك وإن هنته هانك.','لسانك','[]','[]','',1),
('letters-cc76d0e4882e','letters','ar','إذا حضرت الملائكة غابت الشياطين','الملائكة','[]','[]','',1),
('letters-96b87ccc9777','letters','ar','ليس كل من تاه ضائعًا.','ضائعًا','[]','[]','',1),
('letters-7c0943d88cbd','letters','en','Opportunity knocks but once.','opportunity','[]','[]','',1),
('letters-6ba7c287bc62','letters','en','The moon does not heed the barking of dogs.','moon','[]','[]','',1),
('letters-55b832fcf8b1','letters','en','Fine feathers make fine birds.','feathers','[]','[]','',1),
('letters-cf4bd018d89d','letters','en','Prevention is better than cure.','prevention','[]','[]','',1),
('letters-cd0e56f150b8','letters','en','Procrastination is the thief of time.','thief','[]','[]','',1),
('letters-7e89e028fe5b','letters','en','If you pay peanuts, you get monkeys.','peanuts','[]','[]','',1),
('letters-adb589296c88','letters','en','Don''t make a mountain out of a molehill.','mountain','[]','[]','',1),
('letters-c7606471d243','letters','ar','من طارد أرنبين لم يمسك أيًّا منهما.','أرنبين','[]','[]','',1),
('letters-637283c6cd5e','letters','en','The fool speaks, the wise man listens.','listens','[]','[]','',1),
('letters-4b93afd87e0a','letters','en','There''s no place like home.','place','[]','[]','',1),
('letters-6719b2de1db5','letters','en','He who speaks much is much mistaken.','mistaken','[]','[]','',1),
('letters-bbbf49da96ef','letters','en','A man is known by the company he keeps.','company','[]','[]','',1),
('letters-2837af8b5e8a','letters','en','The truth will out.','truth','[]','[]','',1),
('letters-98868b787950','letters','en','A cat may look at a king.','king','[]','[]','',1),
('letters-98ede56108f3','letters','ar','الجار قبل الدار.','الدار','[]','[]','',1),
('letters-8cebbd9dc123','letters','ar','من خاف سلم.','سلم','[]','[]','',1),
('letters-b4939609a83c','letters','en','To err is human; to forgive, divine.','forgive','[]','[]','',1),
('letters-4546d22a4561','letters','ar','لا تُدار الطاحونة بنفخ الكير.','الطاحونة','[]','[]','',1),
('letters-89c327589b4d','letters','en','Character is a diamond that scratches every other stone.','diamond','[]','[]','',1),
('letters-8b4d6f4d0e08','letters','ar','أذناك لا تورطانك لكن لسانك يفعل.','لسانك','[]','[]','',1),
('letters-2841ce9560e6','letters','en','Youth is wasted on the young.','wasted','[]','[]','',1),
('letters-f6868cffb8bd','letters','en','Bullies are always cowards.','bullies','[]','[]','',1),
('letters-6f82495dbff3','letters','en','Every rose has its thorn.','thorn','[]','[]','',1),
('letters-3dbb5cd03fbb','letters','en','A house divided against itself cannot stand.','divided','[]','[]','',1),
('letters-bd8d2253c2d8','letters','en','If you want peace, prepare for war.','prepare','[]','[]','',1),
('letters-dc05885ac5d1','letters','ar','تجري الرياح بما لا تشتهي السفن.','السفن','[]','[]','',1),
('letters-b112df979cd1','letters','en','Curiosity killed the cat.','curiosity','[]','[]','',1),
('letters-51e74e9afbae','letters','en','A small leak will sink a great ship.','leak','[]','[]','',1),
('letters-a4808400b0a0','letters','en','Between friends, frequent reproof makes the friendship distant.','distant','[]','[]','',1),
('letters-9ca83058fc4e','letters','ar','كلما عرفت أكثر احتجت أقل.','احتجت','[]','[]','',1),
('letters-9f46f2404d5b','letters','ar','من يبني على الرمل يبني للسقوط.','الرمل','[]','[]','',1),
('letters-b53fe95ac053','letters','en','All that glitters is not gold.','glitters','[]','[]','',1),
('letters-1c836c01de8a','letters','ar','جنت على نفسها براقش.','براقش','[]','[]','',1),
('letters-7984c6c67c55','letters','en','Misery loves company.','misery','[]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-71e96bf781ed','letters','en','The eye is bigger than the belly.','belly','[]','[]','',1),
('letters-2f00e02415a2','letters','ar','عصفور في اليد خير من عشرة على الشجرة','عصفور','[]','[]','',1),
('letters-3f9f273dfa04','letters','ar','الإيجاز روح الذكاء.','الإيجاز','[]','[]','',1),
('letters-0e926af22465','letters','ar','العلم في الصغر كالنقش على الحجر.','الحجر','[]','[]','',1),
('letters-3c023326c03b','letters','en','If you want to know a man''s character, give him power.','power','[]','[]','',1),
('letters-7b58f96991cf','letters','en','The sun shines even on the wicked (Greek).','shines','[]','[]','',1),
('letters-b41b529845be','letters','en','Fortune favors the bold.','bold','[]','[]','',1),
('letters-7cebe6a9b1dc','letters','en','Liars should have good memories.','memories','[]','[]','',1),
('letters-f87de3b72f4d','letters','ar','القلوب عند بعضها','القلوب','[]','[]','',1),
('letters-4aa3d061e8eb','letters','en','You catch more flies with honey than with vinegar.','honey','[]','[]','',1),
('letters-f2a2a8b1be34','letters','en','Familiarity breeds contempt.','contempt','[]','[]','',1),
('letters-d9230168446c','letters','en','He who hesitates is lost.','hesitates','[]','[]','',1),
('letters-356231e93a01','letters','en','Brevity is the soul of wit.','brevity','[]','[]','',1),
('letters-4b2c2c8e454b','letters','ar','الصديق وقت الضيق.','الضيق','[]','[]','',1),
('letters-cac9b00cc500','letters','ar','أعظم ثروة فقر الرغبات.','الرغبات','[]','[]','',1),
('letters-61acc8ddbee7','letters','ar','أحب جارك ولا تهدم سورك.','سورك','[]','[]','',1),
('letters-cf64d3c7d272','letters','en','A lucky man is one who can lay a firm foundation with the bricks others throw at him.','foundation','[]','[]','',1),
('letters-3ec2bf639ec4','letters','ar','الجزاء من جنس العمل','العمل','[]','[]','',1),
('letters-812513e856f2','letters','en','A friend in need is a friend indeed.','indeed','[]','[]','',1),
('letters-6d19b22fb0b5','letters','en','Strike while the iron is hot.','iron','[]','[]','',1),
('letters-8f53e18b8e4b','letters','ar','اصوِب نحو القمر، فإن أخطأت وصلت إلى النجوم.','النجوم','[]','[]','',1),
('letters-d847d45306ba','letters','ar','الكلام اللين لا يكسر عظمًا لكنه قد يكسر قلبًا.','قلبًا','[]','[]','',1),
('letters-5486dd5b7cf8','letters','ar','كثير الكلام كثير الخطأ.','الخطأ','[]','[]','',1),
('letters-344644ad2bd2','letters','ar','من كُتب عليه الشنق لن يغرق.','يغرق','[]','[]','',1),
('letters-9b28ffa7b9f3','letters','en','He who pays the piper calls the tune.','tune','[]','[]','',1),
('letters-3deb057e7901','letters','ar','من استرعى الذئب فقد ظلم.','الذئب','[]','[]','',1),
('letters-5ed323964561','letters','en','Seeing is believing.','believing','[]','[]','',1),
('letters-4e8010dff2cd','letters','en','Better to be the head of a dog than the tail of a lion.','lion','[]','[]','',1),
('letters-ef0b576bee4a','letters','en','Better an ounce of luck than a pound of gold.','luck','[]','[]','',1),
('letters-5ca295f83079','letters','en','Money is a good servant but a bad master.','servant','[]','[]','',1),
('letters-128b2acabb61','letters','ar','من تدخل فيما لا يعنيه لقي ما لا يرضيه.','يعنيه','[]','[]','',1),
('letters-f9fb11aa91be','letters','ar','الغائب حجته معه','حجته','[]','[]','',1),
('letters-6c0337ba282a','letters','ar','رب ضارة نافعة','نافعة','[]','[]','',1),
('letters-1f00e78b7094','letters','ar','ما كل ما يتمنى المرء يدركه.','يتمنى','[]','[]','',1),
('letters-d8ea9f4e27c3','letters','en','Life is a bridge; cross over it, but build no house on it.','bridge','[]','[]','',1),
('letters-7b5be2254e55','letters','ar','من ترك ما لا يعنيه نال ما يرضيه.','يعنيه','[]','[]','',1),
('letters-b63e5795d118','letters','en','Out of sight, out of mind.','mind','[]','[]','',1),
('letters-e8405eee476a','letters','ar','رضا الناس غاية لا تدرك.','غاية','[]','[]','',1),
('letters-7c7923826299','letters','en','Make hay while the sun shines.','shines','[]','[]','',1),
('letters-d1d946f9e8eb','letters','en','Good fences make good neighbors.','neighbors','[]','[]','',1),
('letters-53c0b08b200d','letters','en','Don''t throw stones at the sun; you''ll only hit yourself.','yourself','[]','[]','',1),
('letters-13e1f8db07c6','letters','en','You can''t fight City Hall.','hall','[]','[]','',1),
('letters-9692615c557c','letters','en','You can''t get blood from a stone.','blood','[]','[]','',1),
('letters-8cc6a2064966','letters','en','The best things in life are free.','free','[]','[]','',1),
('letters-809b0aa036b8','letters','en','Misfortune makes us wise.','misfortune','[]','[]','',1),
('letters-9946dab13a72','letters','ar','ضربني وبكى وسبقني واشتكى.','سبقني','[]','[]','',1),
('letters-07b4fd5fce56','letters','en','The road to hell is paved with good intentions.','intentions','[]','[]','',1),
('letters-dbc04f5e3421','letters','ar','لا تكن يابساً فتكسر ولا ليناً فتعصر.','يابساً','[]','[]','',1),
('letters-86361a576faa','letters','en','Every dog has its day.','dog','[]','[]','',1),
('letters-3827eb2c2d14','letters','ar','الجبناء يموتون مرات قبل موتهم.','الجبناء','[]','[]','',1),
('letters-b7fb895bf6b9','letters','en','Time flies when you''re having fun.','flies','[]','[]','',1),
('letters-5b961ccc4c6f','letters','en','Don''t change horses in midstream.','midstream','[]','[]','',1),
('letters-9df075f20a38','letters','ar','أعلى غصن ليس دائمًا الأكثر أمانًا.','أمانًا','[]','[]','',1),
('letters-2c52f89f34ee','letters','en','If you don''t change direction, you may end up where you''re heading.','direction','[]','[]','',1),
('letters-fc2431b56132','letters','en','The boughs that bear most hang lowest.','boughs','[]','[]','',1),
('letters-0bafc082e56b','letters','en','The squeaky wheel gets the grease.','grease','[]','[]','',1),
('letters-12eac8a92e72','letters','ar','الازدراء طريق الخطر.','الخطر','[]','[]','',1),
('letters-300283f22919','letters','en','There''s no smoke without fire.','smoke','[]','[]','',1),
('letters-a2644034cade','letters','en','You are never too old to learn.','learn','[]','[]','',1),
('letters-121e8f607ea9','letters','en','Once bitten, twice shy.','bitten','[]','[]','',1),
('letters-95604e5bc882','letters','ar','أهل مكة أدرى بشعابها.','شعابها','[]','[]','',1),
('letters-0a1af6180eb4','letters','en','Tomorrow is often the busiest day of the week.','busiest','[]','[]','',1),
('letters-4bd878835749','letters','en','Believe nothing of what you hear and only half of what you see.','half','[]','[]','',1),
('letters-9029582d3463','letters','en','Soft words break no bones, but they can break the heart.','heart','[]','[]','',1),
('letters-ec2c58e7baab','letters','ar','من نام مع الكلاب استيقظ بالبراغيث.','البراغيث','[]','[]','',1),
('letters-85ef8920a2b8','letters','ar','من شب على شيء شاب عليه','شاب','[]','[]','',1),
('letters-814313ee3820','letters','en','A locked door keeps out only the honest man.','locked','[]','[]','',1),
('letters-c8f69f5ebbfe','letters','ar','أعطِ الخبز لخبازه ولو أكل نصفه','لخبازه','[]','[]','',1),
('letters-1b7d982a0b35','letters','ar','الثالثة ثابتة.','الثالثة','[]','[]','',1),
('letters-3ac87063ec48','letters','ar','إذا كان الكلام من فضة فالسكوت من ذهب.','فضة','[]','[]','',1),
('letters-eef986234824','letters','ar','أنجز حر ما وعد','وعد','[]','[]','',1),
('letters-7ea3420fe757','letters','en','If at first you don''t succeed, try, try again.','succeed','[]','[]','',1),
('letters-848cb53e7897','letters','en','Slow and steady wins the race.','steady','[]','[]','',1),
('letters-83453ca6e17b','letters','ar','الحظ هو التقاء الاستعداد بالفرصة.','الاستعداد','[]','[]','',1),
('letters-8606a5bc2834','letters','en','Measure twice, cut once.','measure','[]','[]','',1),
('letters-1938c1b39e3a','letters','en','Charity begins at home.','charity','[]','[]','',1),
('letters-4d6b5edf700c','letters','en','Honey in the mouth, a dagger in the heart.','dagger','[]','[]','',1),
('letters-38bf5b2ff4ba','letters','en','Cut your coat according to your cloth.','cloth','[]','[]','',1),
('letters-52fcb929bcb1','letters','ar','من تأنى نال ما تمنى','تأنى','[]','[]','',1),
('letters-81578d1ff2df','letters','ar','مصائب قوم عند قوم فوائد.','مصائب','[]','[]','',1),
('letters-83c99f5e6326','letters','en','Every man is a king in his own castle.','castle','[]','[]','',1),
('letters-9b59a7f4322b','letters','en','Habit is second nature.','habit','[]','[]','',1),
('letters-53940adcfb58','letters','en','It takes a village to raise a child.','village','[]','[]','',1),
('letters-2bd34821f658','letters','en','He who has a "why" to live can bear almost any "how" (German).','why','[]','[]','',1),
('letters-3e9444528457','letters','ar','رب رمية من غير رام.','رمية','[]','[]','',1),
('letters-6ea2f2c0c4ca','letters','en','Better a witty fool than a foolish wit.','witty','[]','[]','',1),
('letters-e1d84b9aed04','letters','ar','قطع جهيزة قول كل خطيب.','جهيزة','[]','[]','',1),
('letters-02affc406782','letters','en','One should not use a cannon to kill a fly.','cannon','[]','[]','',1),
('letters-cddcf6a39056','letters','ar','القمر لا يلتفت إلى نباح الكلاب.','القمر','[]','[]','',1),
('letters-763861dd4918','letters','ar','لسانك ميزانك.','ميزانك','[]','[]','',1),
('letters-18b1394eaeb8','letters','en','Even a fly has a shadow (Latin).','shadow','[]','[]','',1),
('letters-5f41e6cfab6f','letters','en','You can lead a horse to water, but you can''t make him drink.','horse','[]','[]','',1),
('letters-2e40e5ad26a2','letters','en','You cannot make a windmill go with a pair of bellows.','windmill','[]','[]','',1),
('letters-469817f79fff','letters','en','Better a living beggar than a dead king.','beggar','[]','[]','',1),
('letters-43968280f827','letters','ar','من يملك ساعة يعرف الوقت، ومن يملك ساعتين يشك.','يشك','[]','[]','',1),
('letters-73cb446ec2a9','letters','en','Like mother, like daughter.','daughter','[]','[]','',1),
('letters-318b91191d70','letters','en','Empty vessels make the most noise.','noise','[]','[]','',1),
('letters-b1947cbd1ce6','letters','ar','اتق غضبة الحليم.','الحليم','[]','[]','',1),
('letters-0929ba3fba86','letters','en','Virtue is its own reward.','virtue','[]','[]','',1),
('letters-ac49678a3649','letters','en','Sleep is the brother of death.','brother','[]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-a978a32d5772','letters','en','Don''t put all your eggs in one basket.','basket','[]','[]','',1),
('letters-304eb37132b8','letters','en','Truth is stranger than fiction.','fiction','[]','[]','',1),
('letters-afd6114bfa11','letters','en','Every garden has its weeds.','weeds','[]','[]','',1),
('letters-7d43278d554d','letters','en','The best time to plant a tree was 20 years ago. The second best time is now.','now','[]','[]','',1),
('letters-1ae1a679061a','letters','ar','من أراد صعود السلم بدأ من أسفله.','أسفله','[]','[]','',1),
('letters-469c804ea7e1','letters','en','The forest provides food to the hunter, but only if he is awake (Akan).','awake','[]','[]','',1),
('letters-4da9108b497b','letters','ar','كلمة للعاقل تكفي.','تكفي','[]','[]','',1),
('letters-c890b237b5bd','letters','en','If you can''t beat them, join them.','join','[]','[]','',1),
('letters-f27dbdbbf6e9','letters','en','A bad workman always blames his tools.','tools','[]','[]','',1),
('letters-0b2e112925e4','letters','en','A good beginning makes a good ending.','ending','[]','[]','',1),
('letters-84d0e07008b7','letters','ar','كثيرون يقبّلون اليد التي يتمنون قطعها.','اليد','[]','[]','',1),
('letters-abadd9e38638','letters','ar','رب كلمة قالت لصاحبها دعني','كلمة','[]','[]','',1),
('letters-47ad448bae16','letters','en','Children are the poor man''s riches.','children','[]','[]','',1),
('letters-15aee21f8853','letters','en','Lost time is never found again.','found','[]','[]','',1),
('letters-0ca5a0687a6c','letters','ar','الأنهار العميقة صامتة والضحلة صاخبة.','صامتة','[]','[]','',1),
('letters-7e8efb49688c','letters','en','The third time is the charm.','third','[]','[]','',1),
('letters-6b9424d0c26a','letters','ar','البيت الذي لا يدخله الضوء يدخله الطبيب.','الضوء','[]','[]','',1),
('letters-b18107dea758','letters','ar','خاتمة الخير خير من بدايته.','خاتمة','[]','[]','',1),
('letters-c157aaaedc69','letters','en','A fallen leaf is a signal to the world.','leaf','[]','[]','',1),
('letters-d820504b14cd','letters','en','An apple a day keeps the doctor away.','apple','[]','[]','',1),
('letters-667b235b61d8','letters','ar','رحم الله امرءًا أهدى إليّ عيوبي','عيوبي','[]','[]','',1),
('letters-cfd1b577b0da','letters','ar','من أراد أكل الجوز كسر قشره.','قشره','[]','[]','',1),
('letters-a273cff44e14','letters','en','A bird in the hand is worth two in the bush.','hand','[]','[]','',1),
('letters-4cb5c7640267','letters','en','Better to ask a question and be a fool for five minutes than never to ask and be a fool forever.','forever','[]','[]','',1),
('letters-96436e0e2ab8','letters','en','No man is an island.','island','[]','[]','',1),
('letters-47eec891392f','letters','en','Don''t judge a book by its cover.','cover','[]','[]','',1),
('letters-5e7360b3e572','letters','en','If you don''t have anything nice to say, don''t say anything at all.','nice','[]','[]','',1),
('letters-bf82a96b1597','letters','ar','البعيد عن العين بعيد عن القلب.','القلب','[]','[]','',1),
('letters-8350198d7fbb','letters','en','First come, first served.','served','[]','[]','',1),
('letters-8396e3949095','letters','en','Change is as good as a rest.','rest','[]','[]','',1),
('letters-d01f77d3a219','letters','ar','ما حك جلدك مثل ظفرك.','جلدك','[]','[]','',1),
('letters-2af296a2e7be','letters','en','A nod is as good as a wink to a blind horse.','wink','[]','[]','',1),
('letters-930c26c4da10','letters','en','Lend your money and lose your friend.','friend','[]','[]','',1),
('letters-db24578c7336','letters','en','Better safe than sorry.','safe','[]','[]','',1),
('letters-03e8c59838d5','letters','en','Character is what you do when no one is looking.','character','[]','[]','',1),
('letters-9c90f9753481','letters','en','Little by little, the bird builds its nest.','nest','[]','[]','',1),
('letters-4aa9e60bdc35','letters','ar','يُصلح الجسر قبل الفيضان.','الفيضان','[]','[]','',1),
('letters-c96ec19f911e','letters','en','The eyes are the windows to the soul.','soul','[]','[]','',1),
('letters-e64fc8a17840','letters','en','Hunger is the best sauce.','sauce','[]','[]','',1),
('letters-9dd40d238014','letters','en','You cannot carry two watermelons in one hand (Turkish).','watermelons','[]','[]','',1),
('letters-7ce99bd86db8','letters','en','One swallow does not make a summer.','swallow','[]','[]','',1),
('letters-92c70118a4b8','letters','en','The morning hour has gold in its mouth.','morning','[]','[]','',1),
('letters-2decc900b055','letters','ar','من جاور السعيد يسعد.','السعيد','[]','[]','',1),
('letters-f3b43752ae1e','letters','en','To know the road ahead, ask those coming back.','road','[]','[]','',1),
('letters-c1e8c215ffa0','letters','en','Contentment is better than riches.','contentment','[]','[]','',1),
('letters-ee0dec8f1ba6','letters','en','Don''t bite the hand that feeds you.','feeds','[]','[]','',1),
('letters-0b1a2d69e637','letters','en','Lend only what you can afford to lose.','afford','[]','[]','',1),
('letters-011fdc3a27e7','letters','en','No pain, no gain.','gain','[]','[]','',1),
('letters-afa49cd9cabd','letters','en','A goat''s hide smells like a goat (African).','hide','[]','[]','',1),
('letters-d1300011e549','letters','en','Many a mickle makes a muckle (Many small things make a big thing).','mickle','[]','[]','',1),
('letters-66aee1618631','letters','en','A beautiful grape is often sour (Persian).','grape','[]','[]','',1),
('letters-215de805f58a','letters','ar','الاعتراف بالحق فضيلة.','فضيلة','[]','[]','',1),
('letters-7aa2634cc4cb','letters','ar','لا يضيع حق وراءه مطالب.','مطالب','[]','[]','',1),
('letters-17d9bf6af095','letters','en','When the cat''s away, the mice will play.','mice','[]','[]','',1),
('letters-7dd7b1a68079','letters','ar','أول الشجرة بذرة.','بذرة','[]','[]','',1),
('letters-a6bde083162e','letters','en','Even a monkey falls from a tree (Japanese).','monkey','[]','[]','',1),
('letters-1262327cf427','letters','en','The more you know, the less you need.','less','[]','[]','',1),
('letters-2128d1018c3f','letters','en','An empty bag cannot stand upright.','upright','[]','[]','',1),
('letters-2941f7568096','letters','en','A book is like a garden carried in the pocket (Chinese).','garden','[]','[]','',1),
('letters-e36af3c3fa6a','letters','ar','السكوت علامة الرضا.','الرضا','[]','[]','',1),
('letters-1069b2340560','letters','en','Good things come to those who wait.','wait','[]','[]','',1),
('letters-1202a12d5248','letters','ar','العين نافذة الروح.','الروح','[]','[]','',1),
('letters-7c314b0cb9cb','letters','ar','لا إنسان جزيرة معزولة.','جزيرة','[]','[]','',1),
('letters-e76bd94575df','letters','en','Too many cooks spoil the broth.','broth','[]','[]','',1),
('letters-eb326d790ec8','letters','en','The coffee is only as good as the water (Ethiopian).','water','[]','[]','',1),
('letters-edad0427bcf4','letters','en','Don''t bite off more than you can chew.','chew','[]','[]','',1),
('letters-57edfcb5faa5','letters','en','Silence is golden.','golden','[]','[]','',1),
('letters-e510952df32e','letters','ar','لكل حديقة أعشابها الضارة.','الضارة','[]','[]','',1),
('letters-acadad5d7b3f','letters','en','One man''s meat is another man''s poison.','poison','[]','[]','',1),
('letters-265b4322f431','letters','ar','البذخ عبء والبساطة نعمة.','البساطة','[]','[]','',1),
('letters-580c50a7651b','letters','en','All work and no play makes Jack a dull boy.','jack','[]','[]','',1),
('letters-d6039bf0feb4','letters','en','Small is beautiful.','small','[]','[]','',1),
('letters-fc2780d47e5b','letters','ar','الجمال جمال الروح.','الروح','[]','[]','',1),
('letters-0440ea0f66d9','letters','en','He who is content has enough.','enough','[]','[]','',1),
('letters-7b53a33ecb57','letters','en','Learn from the mistakes of others; you can''t live long enough to make them all yourself.','mistakes','[]','[]','',1),
('letters-fa726840de07','letters','en','Every medal has two sides.','medal','[]','[]','',1),
('letters-ae96614ff461','letters','en','Enough is as good as a feast.','feast','[]','[]','',1),
('letters-47341e28af48','letters','ar','إذا هبت رياحك فاغتنمها','رياحك','[]','[]','',1),
('letters-ff7bc3f0b75f','letters','en','Rats desert a sinking ship.','sinking','[]','[]','',1),
('letters-58806b2f71dc','letters','en','Wealth like rheum is a sickness; it''s better to be rid of it.','rheum','[]','[]','',1),
('letters-aaa9ec4d1d21','letters','en','There is nothing new under the sun.','nothing','[]','[]','',1),
('letters-d0deebdcd902','letters','ar','الطائر إن لم يطر جاع.','جاع','[]','[]','',1),
('letters-23557f66645a','letters','en','Necessity has no holiday.','necessity','[]','[]','',1),
('letters-99c18ce232ec','letters','ar','إن غدا لناظره قريب','قريب','[]','[]','',1),
('letters-a792e405a436','letters','ar','الأرض تعطي كل شيء وتسترد كل شيء.','الأرض','[]','[]','',1),
('letters-3703cfffb194','letters','en','Don''t throw the baby out with the bathwater.','bathwater','[]','[]','',1),
('letters-5a6a42504919','letters','ar','جيل يزرع الشجر وآخر يستظل به.','يستظل','[]','[]','',1),
('letters-daa5b44afb78','letters','ar','من أراد القفز عاليًا فعليه أن يثني ركبتيه.','ركبتيه','[]','[]','',1),
('letters-4b6e0d8987cc','letters','ar','عدو عاقل خير من صديق جاهل.','جاهل','[]','[]','',1),
('letters-042e9f575cdb','letters','en','Growth is painful. Change is painful. But nothing is as painful as staying stuck.','stuck','[]','[]','',1),
('letters-98feb9da4a35','letters','ar','خير الأمور أوسطها','أوسطها','[]','[]','',1),
('letters-c0dc937f2741','letters','ar','الغالي ثمنه فيه','ثمنه','[]','[]','',1),
('letters-a8ac4f297969','letters','en','Don''t sail out farther than you can row back.','farther','[]','[]','',1),
('letters-e250edd5f03f','letters','en','Scorn at your own peril.','peril','[]','[]','',1),
('letters-c6d3ccac2d7c','letters','en','A wolf in sheep''s clothing.','wolf','[]','[]','',1),
('letters-20d0af6a308f','letters','ar','خير الغنى غنى النفس.','النفس','[]','[]','',1),
('letters-e54908b7c496','letters','ar','إذا غامرتَ في شرفٍ مروم فلا تقنعْ بما دون النجوم','النجوم','[]','[]','',1),
('letters-c75308df933a','letters','ar','الإصبع الجاف لا يلتقط ملحًا.','ملحًا','[]','[]','',1),
('letters-0549ec0ac5a1','letters','ar','لسنا شيوخًا حتى تحل الندم محل الأحلام.','الندم','[]','[]','',1),
('letters-4ad0c3d5237f','letters','en','Bad luck comes in threes.','threes','[]','[]','',1)
on conflict (id) do nothing;

insert into hikmah.content(id,kind,locale,prompt,answer,choices,clues,explanation,active) values
('letters-7be5bb0909a7','letters','en','Constant dripping wears away the stone.','dripping','[]','[]','',1),
('letters-d995cb959180','letters','ar','المكتوب على الجبين لازم تشوفه العين.','الجبين','[]','[]','',1),
('letters-00fec40084b1','letters','en','If the bird doesn''t fly, it will starve (African).','starve','[]','[]','',1),
('letters-ca1c0b4f54e4','letters','ar','اسأل مجرب ولا تسأل طبيب','مجرب','[]','[]','',1),
('letters-84a25944d117','letters','en','A dry finger cannot pick up salt.','salt','[]','[]','',1),
('letters-49b89244933a','letters','ar','الكتاب يقرأ من عنوانه','عنوانه','[]','[]','',1),
('letters-887a86bc59d2','letters','en','Necessity is the mother of invention.','invention','[]','[]','',1),
('letters-f72b71ffbc43','letters','ar','حبل الكذب قصير','قصير','[]','[]','',1),
('letters-0151015addc1','letters','ar','فرخ البط عوام.','البط','[]','[]','',1),
('letters-31006cd9dd54','letters','en','A leopard cannot change its spots.','spots','[]','[]','',1),
('letters-0e60736d046d','letters','en','It''s better to light a candle than to curse the darkness.','candle','[]','[]','',1),
('letters-b508baed9e63','letters','ar','من يحرّك جبلًا يبدأ بإزالة الحجارة الصغيرة.','الحجارة','[]','[]','',1),
('letters-1b917547c62c','letters','en','Beggars can''t be choosers.','beggars','[]','[]','',1),
('letters-5ed02cf447d3','letters','ar','عسل في الفم وخنجر في القلب.','خنجر','[]','[]','',1),
('letters-e64df0f393f9','letters','ar','سلامة الإنسان في حلاوة اللسان','اللسان','[]','[]','',1),
('letters-f70bf070626e','letters','en','He who has burned his tongue on hot soup blows on cold yogurt (Turkish).','yogurt','[]','[]','',1),
('letters-b118d5f5633b','letters','en','Great wealth, great care.','care','[]','[]','',1),
('letters-f8bdf55acbed','letters','en','He who builds on the sand builds for a fall.','sand','[]','[]','',1),
('letters-36e17ecad04a','letters','en','Fortune knocks at least once at every man''s door.','door','[]','[]','',1),
('letters-2aed5e9d06ae','letters','en','Might makes right.','might','[]','[]','',1),
('letters-d6c3db72a64a','letters','en','We are not old until regrets take the place of dreams.','dreams','[]','[]','',1),
('letters-611d988e29e6','letters','ar','لا تدع الشمس تغرب على غضبك.','غضبك','[]','[]','',1),
('letters-633e9a9a7cf9','letters','en','History repeats itself.','repeats','[]','[]','',1),
('letters-8f6df278590b','letters','en','Cowards die many times before their deaths.','cowards','[]','[]','',1),
('letters-9571cff8c739','letters','en','He who would climb the ladder must begin at the bottom.','bottom','[]','[]','',1),
('letters-907745367e08','letters','en','Fall seven times, stand up eight.','eight','[]','[]','',1),
('letters-790cd9c0e7b5','letters','en','To a friend''s house, the way is never long (Danish).','long','[]','[]','',1),
('letters-eaa2ea6b760d','letters','en','Silence is the fence around wisdom.','fence','[]','[]','',1),
('letters-dc09298c5fcd','letters','en','All good things must come to an end.','end','[]','[]','',1),
('letters-e2b8d16da223','letters','ar','الصغير جميل.','الصغير','[]','[]','',1),
('letters-84395b4dd996','letters','en','Necessity makes strange bedfellows.','bedfellows','[]','[]','',1),
('letters-d7e588a051a4','letters','en','It is better to have loved and lost than never to have loved at all.','lost','[]','[]','',1),
('letters-b208148ab782','letters','ar','اللي اختشوا ماتوا','اختشوا','[]','[]','',1),
('letters-3daab27695fe','letters','ar','الموت يسوّي بين الجميع.','الموت','[]','[]','',1),
('letters-5ab7636f2751','letters','ar','رجع بخفي حنين.','حنين','[]','[]','',1),
('letters-6c55625a3328','letters','ar','الصلح سيد الأحكام.','الصلح','[]','[]','',1),
('letters-874b5cfb407f','letters','ar','كثرة الطباخين تحرق الطبخة.','الطباخين','[]','[]','',1),
('letters-d626bde4aa69','letters','en','A clear conscience is a soft pillow.','pillow','[]','[]','',1),
('letters-99c914624983','letters','en','A thousand probabilities do not make one truth (English).','truth','[]','[]','',1),
('letters-dca0bdd37f82','letters','en','A good name is better than riches.','riches','[]','[]','',1),
('letters-c98c2ffa4465','letters','en','You can''t make an omelet without breaking eggs.','eggs','[]','[]','',1),
('letters-d8a117956fb8','letters','en','An old friend is better than two new ones.','friend','[]','[]','',1),
('letters-78ae1c69d08c','letters','en','Half a loaf is better than no bread.','loaf','[]','[]','',1),
('letters-a2b4df96d95b','letters','ar','بلغ السيل الزبى.','الزبى','[]','[]','',1),
('letters-ff641ca2a179','letters','en','Every end is a new beginning.','beginning','[]','[]','',1),
('letters-4517feff53b3','letters','en','Nature does nothing in vain.','vain','[]','[]','',1),
('letters-3b1a9228ed29','letters','ar','إذا أردت أن تطاع فأمر بما يُستطاع','يُستطاع','[]','[]','',1),
('letters-5b16a82ef958','letters','en','United we stand, divided we fall.','united','[]','[]','',1),
('letters-fbcfb34b1390','letters','en','You can''t judge a tree by its bark.','bark','[]','[]','',1),
('letters-50ef4ff3a0b9','letters','en','He who moves a mountain begins by carrying away small stones.','stones','[]','[]','',1),
('letters-d1ffd3d88a6d','letters','en','Variety is the spice of life.','spice','[]','[]','',1),
('letters-e177cb757986','letters','ar','درهم دينار ولا خسارة جار','جار','[]','[]','',1),
('letters-4b8b16620dbb','letters','en','Time heals all wounds.','wounds','[]','[]','',1),
('cryptogram-a126216f1ad1','cryptogram','en','BUILD WITH PATIENCE AND CARE','BUILD WITH PATIENCE AND CARE','[]','[{"word":"BUILD","hint":"Construct or create"},{"word":"WITH","hint":"Together or using"},{"word":"PATIENCE","hint":"Ability to wait calmly"},{"word":"AND","hint":"Connector"},{"word":"CARE","hint":"Attention and concern"}]','',1),
('cryptogram-3625b3bf3fbb','cryptogram','en','MOVE SLOWLY AND THINK AHEAD','MOVE SLOWLY AND THINK AHEAD','[]','[{"word":"MOVE","hint":"Proceed or advance"},{"word":"SLOWLY","hint":"At a gradual pace"},{"word":"AND","hint":"Connector"},{"word":"THINK","hint":"Consider carefully"},{"word":"AHEAD","hint":"Looking to the future"}]','',1),
('cryptogram-f44d8d7d1d1e','cryptogram','en','SEEK TRUTH AND AVOID NOISE','SEEK TRUTH AND AVOID NOISE','[]','[{"word":"SEEK","hint":"Search or look for"},{"word":"TRUTH","hint":"Facts or reality"},{"word":"AND","hint":"Connector"},{"word":"AVOID","hint":"Stay away from"},{"word":"NOISE","hint":"Distractions or irrelevant information"}]','',1),
('cryptogram-f8b9e6daffbf','cryptogram','en','FINISH WHAT YOU START','FINISH WHAT YOU START','[]','[{"word":"FINISH","hint":"Complete or conclude"},{"word":"WHAT","hint":"The thing that"},{"word":"YOU","hint":"Yourself"},{"word":"START","hint":"Begin"}]','',1),
('cryptogram-ff3592efb719','cryptogram','en','LEARN DAILY AND GROW','LEARN DAILY AND GROW','[]','[{"word":"LEARN","hint":"Study or gain knowledge"},{"word":"DAILY","hint":"Every day"},{"word":"AND","hint":"Connector"},{"word":"GROW","hint":"Increase or develop"}]','',1),
('cryptogram-2664623ec7fb','cryptogram','en','LISTEN MORE AND SPEAK LESS','LISTEN MORE AND SPEAK LESS','[]','[{"word":"LISTEN","hint":"Hear attentively"},{"word":"MORE","hint":"Greater amount"},{"word":"AND","hint":"Connector"},{"word":"SPEAK","hint":"Talk or express"},{"word":"LESS","hint":"Smaller amount"}]','',1),
('cryptogram-42de1f99b677','cryptogram','en','TRUST YOUR JUDGMENT','TRUST YOUR JUDGMENT','[]','[{"word":"TRUST","hint":"Have confidence in"},{"word":"YOUR","hint":"Belonging to you"},{"word":"JUDGMENT","hint":"Decision or opinion"}]','',1),
('cryptogram-5e96ec0f9e29','cryptogram','en','TRUST THE PROCESS AND CONTINUE','TRUST THE PROCESS AND CONTINUE','[]','[{"word":"TRUST","hint":"Have confidence in"},{"word":"THE","hint":"Article"},{"word":"PROCESS","hint":"Series of steps"},{"word":"AND","hint":"Connector"},{"word":"CONTINUE","hint":"Keep going"}]','',1),
('cryptogram-90ea377136e9','cryptogram','en','CREATE VALUE AND STAY HUMBLE','CREATE VALUE AND STAY HUMBLE','[]','[{"word":"CREATE","hint":"Make or produce"},{"word":"VALUE","hint":"Worth or importance"},{"word":"AND","hint":"Connector"},{"word":"STAY","hint":"Remain"},{"word":"HUMBLE","hint":"Modest or unpretentious"}]','',1),
('cryptogram-d1a0e4ee07d2','cryptogram','en','PLAN CAREFULLY AND EXECUTE WELL','PLAN CAREFULLY AND EXECUTE WELL','[]','[{"word":"PLAN","hint":"Prepare or organize"},{"word":"CAREFULLY","hint":"With caution"},{"word":"AND","hint":"Connector"},{"word":"EXECUTE","hint":"Perform or carry out"},{"word":"WELL","hint":"Properly or successfully"}]','',1),
('cryptogram-3afb56bee90a','cryptogram','en','LEAD QUIETLY AND INSPIRE OTHERS','LEAD QUIETLY AND INSPIRE OTHERS','[]','[{"word":"LEAD","hint":"Guide or direct"},{"word":"QUIETLY","hint":"Without noise or show"},{"word":"AND","hint":"Connector"},{"word":"INSPIRE","hint":"Motivate or encourage"},{"word":"OTHERS","hint":"Different people"}]','',1),
('cryptogram-5861a8fd43d6','cryptogram','en','WORK CONSISTENTLY AND IMPROVE','WORK CONSISTENTLY AND IMPROVE','[]','[{"word":"WORK","hint":"Make effort"},{"word":"CONSISTENTLY","hint":"Regularly and reliably"},{"word":"AND","hint":"Connector"},{"word":"IMPROVE","hint":"Get better"}]','',1),
('cryptogram-473358fa996e','cryptogram','en','CHOOSE SIMPLICITY OVER CHAOS','CHOOSE SIMPLICITY OVER CHAOS','[]','[{"word":"CHOOSE","hint":"Decide or select"},{"word":"SIMPLICITY","hint":"Being simple"},{"word":"OVER","hint":"Instead of"},{"word":"CHAOS","hint":"Disorder or confusion"}]','',1),
('cryptogram-efc6a0a8db10','cryptogram','en','VALUE TIME AND USE IT WISELY','VALUE TIME AND USE IT WISELY','[]','[{"word":"VALUE","hint":"Appreciate or treasure"},{"word":"TIME","hint":"Duration or moments"},{"word":"AND","hint":"Connector"},{"word":"USE","hint":"Apply or utilize"},{"word":"IT","hint":"The thing mentioned"},{"word":"WISELY","hint":"With good judgment"}]','',1),
('cryptogram-b8741d676f87','cryptogram','en','ACT CALMLY UNDER PRESSURE','ACT CALMLY UNDER PRESSURE','[]','[{"word":"ACT","hint":"Take action"},{"word":"CALMLY","hint":"In a peaceful manner"},{"word":"UNDER","hint":"In a condition of"},{"word":"PRESSURE","hint":"Stress or difficulty"}]','',1),
('cryptogram-81860d0cf31e','cryptogram','en','PROTECT ENERGY AND SET LIMITS','PROTECT ENERGY AND SET LIMITS','[]','[{"word":"PROTECT","hint":"Guard or defend"},{"word":"ENERGY","hint":"Strength or vitality"},{"word":"AND","hint":"Connector"},{"word":"SET","hint":"Establish or define"},{"word":"LIMITS","hint":"Boundaries or restrictions"}]','',1),
('cryptogram-de704e3ce04e','cryptogram','en','LEARN FROM FAILURE AND ADJUST','LEARN FROM FAILURE AND ADJUST','[]','[{"word":"LEARN","hint":"Gain knowledge"},{"word":"FROM","hint":"Out of or because of"},{"word":"FAILURE","hint":"Lack of success"},{"word":"AND","hint":"Connector"},{"word":"ADJUST","hint":"Modify or adapt"}]','',1),
('cryptogram-c0a8a446ce7f','cryptogram','en','MOVE WITH PURPOSE AND CLARITY','MOVE WITH PURPOSE AND CLARITY','[]','[{"word":"MOVE","hint":"Advance or proceed"},{"word":"WITH","hint":"Together or using"},{"word":"PURPOSE","hint":"Intention or goal"},{"word":"AND","hint":"Connector"},{"word":"CLARITY","hint":"Clear understanding"}]','',1),
('cryptogram-f598daac09c6','cryptogram','en','QUESTION FEAR AND MOVE FORWARD','QUESTION FEAR AND MOVE FORWARD','[]','[{"word":"QUESTION","hint":"Challenge or doubt"},{"word":"FEAR","hint":"Feeling of anxiety"},{"word":"AND","hint":"Connector"},{"word":"MOVE","hint":"Proceed"},{"word":"FORWARD","hint":"Ahead or onward"}]','',1),
('cryptogram-6b9c8dd3dbaf','cryptogram','en','BALANCE AMBITION WITH DISCIPLINE','BALANCE AMBITION WITH DISCIPLINE','[]','[{"word":"BALANCE","hint":"Keep in equilibrium"},{"word":"AMBITION","hint":"Strong desire to succeed"},{"word":"WITH","hint":"Together or using"},{"word":"DISCIPLINE","hint":"Self-control or training"}]','',1),
('cryptogram-1e32a95b8cd8','cryptogram','en','DEVELOP CHARACTER AND CAPABILITY','DEVELOP CHARACTER AND CAPABILITY','[]','[{"word":"DEVELOP","hint":"Build or grow"},{"word":"CHARACTER","hint":"Moral qualities"},{"word":"AND","hint":"Connector"},{"word":"CAPABILITY","hint":"Ability or capacity"}]','',1),
('cryptogram-77a171a27585','cryptogram','en','SIMPLIFY SYSTEMS AND SCALE','SIMPLIFY SYSTEMS AND SCALE','[]','[{"word":"SIMPLIFY","hint":"Make simpler"},{"word":"SYSTEMS","hint":"Organized processes"},{"word":"AND","hint":"Connector"},{"word":"SCALE","hint":"Grow or expand"}]','',1),
('cryptogram-1c5ee513670b','cryptogram','en','HONOR COMMITMENTS AND DELIVER','HONOR COMMITMENTS AND DELIVER','[]','[{"word":"HONOR","hint":"Respect or uphold"},{"word":"COMMITMENTS","hint":"Promises or obligations"},{"word":"AND","hint":"Connector"},{"word":"DELIVER","hint":"Fulfill or provide"}]','',1),
('cryptogram-697c63681a88','cryptogram','en','OBSERVE QUIETLY AND ADAPT','OBSERVE QUIETLY AND ADAPT','[]','[{"word":"OBSERVE","hint":"Watch or notice"},{"word":"QUIETLY","hint":"Without noise"},{"word":"AND","hint":"Connector"},{"word":"ADAPT","hint":"Adjust to new conditions"}]','',1),
('cryptogram-82d3be98142d','cryptogram','en','THINK DEEPLY BEFORE DECIDING','THINK DEEPLY BEFORE DECIDING','[]','[{"word":"THINK","hint":"Consider carefully"},{"word":"DEEPLY","hint":"Thoroughly or profoundly"},{"word":"BEFORE","hint":"Prior to"},{"word":"DECIDING","hint":"Making a choice"}]','',1),
('cryptogram-e0f6dc2b29d7','cryptogram','en','PROTECT TRUST AND REPUTATION','PROTECT TRUST AND REPUTATION','[]','[{"word":"PROTECT","hint":"Guard or defend"},{"word":"TRUST","hint":"Confidence or belief"},{"word":"AND","hint":"Connector"},{"word":"REPUTATION","hint":"Public image or standing"}]','',1),
('cryptogram-6e98888801c9','cryptogram','en','FINISH STRONG AND MOVE ON','FINISH STRONG AND MOVE ON','[]','[{"word":"FINISH","hint":"Complete"},{"word":"STRONG","hint":"With full effort"},{"word":"AND","hint":"Connector"},{"word":"MOVE","hint":"Proceed"},{"word":"ON","hint":"Continue forward"}]','',1),
('cryptogram-d47a10440b70','cryptogram','ar','تحرك بهدوء وفكر للأمام','تحرك بهدوء وفكر للأمام','[]','[{"word":"تحرك","hint":"قم بالحركة"},{"word":"بهدوء","hint":"بدون عجلة"},{"word":"وفكر","hint":"استخدم العقل"},{"word":"للأمام","hint":"في المستقبل"}]','',1),
('cryptogram-0ffd6a64cfaf','cryptogram','ar','اختر بحكمة وعش بحرية','اختر بحكمة وعش بحرية','[]','[{"word":"اختر","hint":"اتخذ قرارا"},{"word":"بحكمة","hint":"بعقل وتفكير"},{"word":"وعش","hint":"اقض حياتك"},{"word":"بحرية","hint":"بدون قيود"}]','',1),
('cryptogram-97276059bf9b','cryptogram','ar','راقب الأنماط وتكيف','راقب الأنماط وتكيف','[]','[{"word":"راقب","hint":"انتبه ولاحظ"},{"word":"الأنماط","hint":"التكرارات والعادات"},{"word":"وتكيف","hint":"اضبط نفسك"}]','',1),
('cryptogram-a0ecef7baf5a','cryptogram','ar','قلل التشتت وركز','قلل التشتت وركز','[]','[{"word":"قلل","hint":"اجعله أقل"},{"word":"التشتت","hint":"عدم التركيز"},{"word":"وركز","hint":"انتبه بشدة"}]','',1),
('cryptogram-6a60f28cf920','cryptogram','ar','تعلم من الخطأ وعدل','تعلم من الخطأ وعدل','[]','[{"word":"تعلم","hint":"اكتسب معرفة"},{"word":"من","hint":"بسبب"},{"word":"الخطأ","hint":"الفشل"},{"word":"وعدل","hint":"صحح الطريق"}]','',1),
('cryptogram-bff23fff6c4a','cryptogram','ar','وازن الطموح بالانضباط','وازن الطموح بالانضباط','[]','[{"word":"وازن","hint":"اجعلهما متساويين"},{"word":"الطموح","hint":"الأهداف العالية"},{"word":"بالانضباط","hint":"التحكم بالنفس"}]','',1),
('cryptogram-b516ce2bdc59','cryptogram','ar','ثق بالمسار واستمر','ثق بالمسار واستمر','[]','[{"word":"ثق","hint":"آمن واطمئن"},{"word":"بالمسار","hint":"الطريق والعملية"},{"word":"واستمر","hint":"لا تتوقف"}]','',1),
('cryptogram-f886c03be2e5','cryptogram','ar','قدر الوقت واستخدمه بحكمة','قدر الوقت واستخدمه بحكمة','[]','[{"word":"قدر","hint":"احترم قيمته"},{"word":"الوقت","hint":"الزمن"},{"word":"واستخدمه","hint":"وظفه"},{"word":"بحكمة","hint":"بذكاء"}]','',1),
('cryptogram-1003bc27d2d4','cryptogram','ar','اعمل باستمرار وتطور','اعمل باستمرار وتطور','[]','[{"word":"اعمل","hint":"ابذل جهدا"},{"word":"باستمرار","hint":"بانتظام"},{"word":"وتطور","hint":"تحسن"}]','',1),
('cryptogram-2b712c8bdf2c','cryptogram','ar','واجه الخوف وتقدم','واجه الخوف وتقدم','[]','[{"word":"واجه","hint":"لا تهرب"},{"word":"الخوف","hint":"القلق"},{"word":"وتقدم","hint":"امش للأمام"}]','',1),
('cryptogram-8182599211e5','cryptogram','ar','احم طاقتك وضع حدودا','احم طاقتك وضع حدودا','[]','[{"word":"احم","hint":"احفظ"},{"word":"طاقتك","hint":"قوتك"},{"word":"وضع","hint":"حدد"},{"word":"حدودا","hint":"قيودا"}]','',1),
('cryptogram-442c38dc7808','cryptogram','ar','بسط الأنظمة ووسع الأثر','بسط الأنظمة ووسع الأثر','[]','[{"word":"بسط","hint":"اجعلها سهلة"},{"word":"الأنظمة","hint":"الطرق"},{"word":"ووسع","hint":"اجعله أكبر"},{"word":"الأثر","hint":"التأثير"}]','',1),
('cryptogram-8795e83641ed','cryptogram','ar','تحرك بهدف ووضوح','تحرك بهدف ووضوح','[]','[{"word":"تحرك","hint":"قم بالحركة"},{"word":"بهدف","hint":"بنية"},{"word":"ووضوح","hint":"بشفافية"}]','',1),
('cryptogram-c198082ec8a5','cryptogram','ar','احترم وقتك وحدودك','احترم وقتك وحدودك','[]','[{"word":"احترم","hint":"قدر"},{"word":"وقتك","hint":"زمنك"},{"word":"وحدودك","hint":"قيودك"}]','',1),
('cryptogram-e7828983bbe3','cryptogram','ar','فكر بهدوء قبل القرار','فكر بهدوء قبل القرار','[]','[{"word":"فكر","hint":"تأمل"},{"word":"بهدوء","hint":"بدون عجلة"},{"word":"قبل","hint":"في وقت سابق"},{"word":"القرار","hint":"الاختيار"}]','',1),
('cryptogram-926295731e3a','cryptogram','ar','اعمل بصمت واستمر','اعمل بصمت واستمر','[]','[{"word":"اعمل","hint":"ابذل جهدا"},{"word":"بصمت","hint":"بدون ضجة"},{"word":"واستمر","hint":"لا تتوقف"}]','',1),
('cryptogram-fd9b5dfd0f17','cryptogram','ar','ركز على الأساسيات','ركز على الأساسيات','[]','[{"word":"ركز","hint":"انتبه بشدة"},{"word":"على","hint":"باتجاه"},{"word":"الأساسيات","hint":"الأمور الرئيسية"}]','',1)
on conflict (id) do nothing;
