'use client';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { type Kind,type Locale,type Puzzle } from '@/lib/game/rules';
export type View='home'|'play'|'multiplayer'|'profile'|'leaderboard'|'settings'|'admin';
export type Profile={id:string;name:string;username:string;country:string;city:string;age_group:string;locale:Locale;avatar:string|null;balance:number;isAdmin:boolean};
export type Player={user:string;name:string;avatar:string|null;wins:number;last_seen:number;left_at:number|null};
export type RoomState={room:{id:string;code:string;kind:Kind;locale:Locale;mode:'solo'|'multi';status:string;host:string;total:number};round:{id:string;number:number;startedAt:number;endedAt:number|null;winner:string|null;outcome:string|null;puzzle:Puzzle;solution:string|null;explanation:string|null;submitted:boolean;deadline:number|null}|null;players:Player[];serverTime:number;me:string;profile:Profile|null;history:{number:number;winner:string|null;outcome:string}[]};
export type Props={locale:Locale;t:(en:string,ar:string)=>string;questionLocale:Locale;setQuestionLocale:(l:Locale)=>void;profile:Profile|null;signed:boolean;refresh:()=>Promise<void>};
export async function api(action:string,body?:Record<string,unknown>,query?:Record<string,string>){const res=await fetch('/api/game'+(body?'':'?'+new URLSearchParams({action,...query})),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})}:{cache:'no-store'});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'Please try again.');return data;}
export function title(k:Kind,l:Locale){return {letters:l==='ar'?'الحروف الناقصة':'Missing Letters',mcq:l==='ar'?'اختيار من متعدد':'Multiple Choice',cryptogram:l==='ar'?'الشفرة':'Cryptogram'}[k]}
export function avatar(p:{name:string;avatar?:string|null}){return p.avatar?<img className="avatar" src={'/api/avatar?key='+encodeURIComponent(p.avatar)} alt=""/>:<span className="avatar">{p.name?.slice(0,1).toUpperCase()||'H'}</span>}
export function Loading(){return <div className="panel" role="status" aria-label="Loading"><div className="skeleton" style={{width:'40%'}}/><div className="skeleton"/><div className="skeleton" style={{width:'70%'}}/></div>}
export function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}
export const kinds:Kind[]=['letters','mcq','cryptogram'];