'use client';
import { Admin } from '@/components/hikmah/admin';
import { Home } from '@/components/hikmah/home';
import { Journey } from '@/components/hikmah/journey';
import { Leaderboard } from '@/components/hikmah/leaderboard';
import { Lobby } from '@/components/hikmah/lobby';
import { Play } from '@/components/hikmah/play';
import { Preferences } from '@/components/hikmah/preferences';
import { api,kinds,type Profile,type View } from '@/components/hikmah/shared';
import { type Locale } from '@/lib/game/rules';
import { Coins,Moon,Settings,Sun,User } from 'lucide-react';
import { useCallback,useEffect,useState } from 'react';
export default function Hikmah({view='home',signedInitially=false}:{view?:View;signedInitially?:boolean}){
 const [locale,setLocale]=useState<Locale>('en'),[questionLocale,setQuestionLocale]=useState<Locale>('en'),[dark,setDark]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState(''),[ready,setReady]=useState(false);
 const t=(en:string,ar:string)=>locale==='ar'?ar:en;
 const refresh=useCallback(async()=>{try{const d=await api('dashboard');setData(d);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{setLocale(localStorage.getItem('hikmah_ui')==='ar'?'ar':'en');setQuestionLocale(localStorage.getItem('hikmah_questions')==='ar'?'ar':'en');setDark(localStorage.getItem('hikmah_theme')==='dark');setReady(true);refresh()},[refresh]);
 useEffect(()=>{if(!ready)return;document.documentElement.classList.toggle('dark',dark);document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';localStorage.setItem('hikmah_ui',locale);localStorage.setItem('hikmah_theme',dark?'dark':'light');localStorage.setItem('hikmah_questions',questionLocale)},[ready,locale,dark,questionLocale]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_solo_game',title:'Start a Hikmah solo game',description:'Create a ten-puzzle solo game and open its play screen. Existing active solo games must be finished or left first.',inputSchema:{type:'object',properties:{game:{type:'string',enum:['letters','mcq','cryptogram']},language:{type:'string',enum:['en','ar']}},required:['game','language'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input:any){if(!input||!kinds.includes(input.game)||!['en','ar'].includes(input.language))throw new Error('Choose a valid game and language.');const result=await api('create',{kind:input.game,locale:input.language,mode:'solo'});window.location.assign('/play?id='+result.id);return {id:result.id,status:'created',path:'/play?id='+result.id};}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const signed=data?.signedIn??signedInitially;const p:Profile|null=data?.profile||null;
 const props={locale,t,questionLocale,setQuestionLocale,profile:p,signed,refresh};
 return <div className="shell" dir={locale==='ar'?'rtl':'ltr'}><header className="topbar"><a className="brand" href="/" aria-label="Hikmah home"><img src="/logo.png" alt=""/><span className="brand-name">Hikmah <small>حكمة</small></span></a><nav className="nav" aria-label={t('Main navigation','القائمة الرئيسية')}>{([['home','/',t('The games','الألعاب')],['multiplayer','/multiplayer',t('Play together','العب مع الأصدقاء')],['leaderboard','/leaderboard',t('Leaderboard','المتصدرون')],['profile','/profile',t('My journey','رحلتي')]] as string[][]).map(([v,href,name])=><a key={v} className={view===v?'active':''} href={href}>{name}</a>)}</nav><div className="top-actions"><button className="icon-btn" onClick={()=>setLocale(locale==='en'?'ar':'en')} aria-label={t('Switch to Arabic','التغيير إلى الإنجليزية')}>{locale==='en'?'ع':'EN'}</button><button className="icon-btn hide-mobile" onClick={()=>setDark(!dark)} aria-label={t('Toggle dark theme','تغيير المظهر')}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button>{p?<a className="balance" href="/profile"><Coins size={15}/><strong>{p.balance}</strong> HR</a>:<a className="btn outline" href={'/login?next='+encodeURIComponent('/'+(view==='home'?'':view))} target="_top"><User size={15}/><span className="account-label">{t('Sign in','دخول')}</span></a>}<a className="icon-btn" href="/settings" aria-label={t('Settings','الإعدادات')}><Settings size={16}/></a></div></header><main className="main">{error&&<div className="notice error" role="alert" style={{marginBottom:24}}>{error} <button onClick={refresh}>{t('Retry','إعادة المحاولة')}</button></div>}{view==='home'?<Home {...props} active={data?.active||[]} counts={data?.counts||[]}/>:view==='play'?<Play {...props}/>:view==='multiplayer'?<Lobby {...props}/>:view==='leaderboard'?<Leaderboard {...props}/>:view==='profile'?<Journey {...props}/>:view==='settings'?<Preferences {...props} dark={dark} setDark={setDark} setLocale={setLocale}/>:<Admin {...props}/>}</main><footer className="footer"><span>Hikmah / حكمة <span style={{marginInlineStart:16}}>{t('A little wisdom, every day.','قليل من الحكمة، كل يوم.')}</span></span><div className="flex-row"><span>{t('Made for curious minds','للعقول الفضولية')}</span>{p?.isAdmin&&<a href="/admin">{t('Administration','الإدارة')}</a>}<a href="/settings">{t('Settings','الإعدادات')}</a></div></footer></div>
}