import {database} from '@/db/raw';
import {identity} from './actor';
export {identity} from './actor';
import seeds from './seed.json';
import {snapshot,publicPuzzle,checkAnswer,solution,reward,ROUND_SECONDS,POINTS,type Kind,type Locale,type Content,type Snapshot} from './rules';
export class GameError extends Error{constructor(message:string,public status=400){super(message)}}
const now=()=>Date.now();const uid=()=>crypto.randomUUID();
export async function one(sql:string,...args:any[]){return database().prepare(sql).bind(...args).first<any>();}
export async function many(sql:string,...args:any[]){return (await database().prepare(sql).bind(...args).all<any>()).results;}
export async function run(sql:string,...args:any[]){return database().prepare(sql).bind(...args).run();}
export async function batch(stmts:[string,any[]][]){return database().batch(stmts.map(([q,a])=>database().prepare(q).bind(...a)));}
export async function init(){if(await one("SELECT value FROM site_settings WHERE key='seed_v1'"))return;const c=seeds as Content[];for(let i=0;i<c.length;i+=25)await batch(c.slice(i,i+25).map(x=>['INSERT OR IGNORE INTO content(id,kind,locale,prompt,answer,choices,clues,explanation) VALUES(?,?,?,?,?,?,?,?)',[x.id,x.kind,x.locale,x.prompt,x.answer,JSON.stringify(x.choices),JSON.stringify(x.clues),x.explanation]]));await run("INSERT OR IGNORE INTO site_settings(key,value) VALUES('seed_v1','1')");}
export async function ensureProfile(u:Awaited<ReturnType<typeof identity>>){if(!u.signed)return null;
 await batch([
 ["INSERT OR IGNORE INTO profiles(id,name,created_at) VALUES(?,?,?)",[u.id,u.name,now()]],
 ["INSERT OR IGNORE INTO wallet(id,user,amount,reason,created_at) VALUES(?,?,20,'Welcome',?)",['welcome:'+u.id,u.id,now()]],
 ]);
 if(u.authUserId)await run('UPDATE profiles SET auth_user_id=? WHERE id=? AND auth_user_id IS NULL',u.authUserId,u.id);
 return profile(u.id);
}
export async function isAdmin(id:string){const a=await one("SELECT value FROM site_settings WHERE key='admin_user'");return a?.value===id;}
export async function profile(id:string){const p=await one('SELECT * FROM profiles WHERE id=?',id);if(!p)return null;return {...p,balance:(await one('SELECT COALESCE(SUM(amount),0) AS balance FROM wallet WHERE user=?',id)).balance,isAdmin:await isAdmin(id)};}
export async function requireAccount(){const u=await identity();if(!u.signed)throw new GameError('Sign in to continue.',401);const p=await ensureProfile(u);if(p?.banned)throw new GameError('This account is suspended.',403);return u;}
export async function requireAdmin(){const u=await requireAccount();if(!await isAdmin(u.id))throw new GameError('Administrator access required.',403);return u;}
function contentRow(r:any):Content{return {...r,choices:JSON.parse(r.choices),clues:JSON.parse(r.clues)};}
export async function createRoom(kind:Kind,locale:Locale,mode:'solo'|'multi',u:Awaited<ReturnType<typeof identity>>){if(!['mcq','letters','cryptogram'].includes(kind)||!['en','ar'].includes(locale))throw new GameError('Choose a game and language.');if(mode==='multi'&&!u.signed)throw new GameError('Sign in to play with friends.',401);
 const active=await one("SELECT r.id FROM rooms r JOIN members m ON m.room=r.id WHERE m.user=? AND m.left_at IS NULL AND r.mode=? AND r.status IN ('waiting','active') AND r.updated_at>? ORDER BY r.created_at DESC LIMIT 1",u.id,mode,now()-3600000);
 if(active)throw new GameError('Finish or leave your current '+mode+' game first.');
 const total=mode==='multi'?5:10;const rows=await many('SELECT c.* FROM content c WHERE c.active=1 AND c.kind=? AND c.locale=? ORDER BY EXISTS(SELECT 1 FROM rounds rr JOIN attempts a ON a.round=rr.id WHERE rr.content_id=c.id AND a.user=?),random() LIMIT ?',kind,locale,u.id,total);
 if(rows.length<(mode==='multi'?5:1))throw new GameError('Not enough puzzles in this language yet.');
 const id=uid(),code=uid().replace(/-/g,'').slice(0,8).toUpperCase(),t=now();
 const q:[string,any[]][]=[['INSERT INTO rooms(id,code,kind,locale,mode,host,status,round,total,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[id,code,kind,locale,mode,u.id,mode==='solo'?'active':'waiting',mode==='solo'?1:0,rows.length,t,t]],['INSERT INTO members(room,user,joined_at,last_seen) VALUES(?,?,?,?)',[id,u.id,t,t]]];
 rows.forEach((c,i)=>q.push(['INSERT INTO rounds(id,room,number,content_id,snapshot,started_at) VALUES(?,?,?,?,?,?)',[uid(),id,i+1,c.id,JSON.stringify(snapshot(contentRow(c))),mode==='solo'&&i===0?t:null]]));await batch(q);return {id,code};
}
export async function joinRoom(code:string,u:Awaited<ReturnType<typeof identity>>){if(!u.signed)throw new GameError('Sign in to join a room.',401);const r=await one("SELECT * FROM rooms WHERE (code=? OR id=?) AND mode='multi'",code.toUpperCase(),code);if(!r)throw new GameError('Room not found.',404);const member=await one('SELECT * FROM members WHERE room=? AND user=?',r.id,u.id);if(member&&!member.left_at)return {id:r.id};if(r.status!=='waiting')throw new GameError('This match has already started.');
 await run("INSERT INTO members(room,user,joined_at,last_seen,left_at) SELECT ?,?,?,?,NULL WHERE (SELECT COUNT(*) FROM members WHERE room=? AND left_at IS NULL)<8 AND EXISTS(SELECT 1 FROM rooms WHERE id=? AND status='waiting') ON CONFLICT(room,user) DO UPDATE SET left_at=NULL,last_seen=excluded.last_seen",r.id,u.id,now(),now(),r.id,r.id);
 const added=await one('SELECT * FROM members WHERE room=? AND user=? AND left_at IS NULL',r.id,u.id);if(!added)throw new GameError('Room is full.');return {id:r.id};}
async function memberRoom(id:string,user:string){const r=await one('SELECT r.* FROM rooms r JOIN members m ON m.room=r.id WHERE r.id=? AND m.user=? AND m.left_at IS NULL',id,user);if(!r)throw new GameError('Join this room to continue.',403);return r;}
export async function startRoom(id:string,user:string){const r=await memberRoom(id,user);if(r.host!==user)throw new GameError('Only the host can start the match.',403);if((await one('SELECT COUNT(*) AS n FROM members WHERE room=? AND left_at IS NULL',id)).n<2)throw new GameError('At least two players are needed.');const t=now()+3000;await batch([["UPDATE rooms SET status='active',round=1,updated_at=? WHERE id=? AND status='waiting'",[now(),id]],["UPDATE rounds SET started_at=? WHERE room=? AND number=1 AND started_at IS NULL AND EXISTS(SELECT 1 FROM rooms WHERE id=? AND status='active')",[t,id,id]]]);}
export async function leaveRoom(id:string,user:string){const r=await memberRoom(id,user);await run('UPDATE members SET left_at=? WHERE room=? AND user=?',now(),id,user);const other=await one('SELECT user FROM members WHERE room=? AND left_at IS NULL ORDER BY joined_at LIMIT 1',id);if(!other)await run("UPDATE rooms SET status='abandoned',updated_at=? WHERE id=? AND status!='finished'",now(),id);else if(r.host===user)await run('UPDATE rooms SET host=? WHERE id=?',other.user,id);}
export async function advance(id:string,user:string,manual=false){let r=await memberRoom(id,user);const t=now();await run('UPDATE members SET last_seen=? WHERE room=? AND user=?',t,id,user);
 // An active participant takes over an absent host after a grace period.
 await run('UPDATE rooms SET host=? WHERE id=? AND host!=? AND EXISTS(SELECT 1 FROM members WHERE room=? AND user=rooms.host AND (last_seen<? OR left_at IS NOT NULL))',user,id,user,id,t-45000);
 if(r.status!=='active')return;
 let rd=await one('SELECT * FROM rounds WHERE room=? AND number=?',id,r.round);if(!rd?.started_at)return;
 if(r.mode==='multi'&&!rd.ended_at){if(t>=rd.started_at+ROUND_SECONDS[r.kind as Kind]*1000)await run("UPDATE rounds SET ended_at=?,outcome='timeout' WHERE id=? AND ended_at IS NULL",t,rd.id);else if(r.kind==='mcq')await run("UPDATE rounds SET ended_at=?,outcome='no_correct' WHERE id=? AND ended_at IS NULL AND (SELECT COUNT(*) FROM attempts WHERE round=?)>=(SELECT COUNT(*) FROM members WHERE room=? AND left_at IS NULL)",t,rd.id,rd.id,id);rd=await one('SELECT * FROM rounds WHERE id=?',rd.id);}
 if(!rd.ended_at)return;
 if(r.mode==='solo'&&!manual)return;
 if(r.mode==='multi'&&t<rd.ended_at+6000)return;
 if(r.round>=r.total){await run("UPDATE rooms SET status='finished',updated_at=? WHERE id=? AND round=? AND status='active'",t,id,r.round);return;}
 await batch([['UPDATE rooms SET round=round+1,updated_at=? WHERE id=? AND round=? AND status=\'active\'',[t,id,r.round]],['UPDATE rounds SET started_at=? WHERE room=? AND number=? AND started_at IS NULL AND EXISTS(SELECT 1 FROM rooms WHERE id=? AND round=?)',[t+(r.mode==='multi'?2000:0),id,r.round+1,id,r.round+1]]]);
}
export async function roomState(id:string,u:Awaited<ReturnType<typeof identity>>){await advance(id,u.id);const r=await memberRoom(id,u.id);const rd=await one('SELECT * FROM rounds WHERE room=? AND number=?',id,r.round);const players=await many("SELECT m.user,m.last_seen,m.left_at,COALESCE(p.name,'Guest') AS name,p.avatar,(SELECT COUNT(*) FROM rounds rr WHERE rr.room=m.room AND rr.winner=m.user) AS wins FROM members m LEFT JOIN profiles p ON p.id=m.user WHERE m.room=? ORDER BY wins DESC,m.joined_at",id);let round=null;if(rd){const s=JSON.parse(rd.snapshot) as Snapshot;const attempt=await one('SELECT correct FROM attempts WHERE round=? AND user=?',rd.id,u.id);round={id:rd.id,number:rd.number,startedAt:rd.started_at,endedAt:rd.ended_at,winner:rd.winner,outcome:rd.outcome,puzzle:publicPuzzle(s),solution:rd.ended_at?solution(s):null,explanation:rd.ended_at?s.explanation:null,submitted:!!attempt&&r.kind==='mcq',deadline:r.mode==='multi'?rd.started_at+ROUND_SECONDS[r.kind as Kind]*1000:null};}
 return {room:{id:r.id,code:r.code,kind:r.kind,locale:r.locale,mode:r.mode,status:r.status,host:r.host,total:r.total},round,players,serverTime:now(),me:u.id,profile:u.signed?await profile(u.id):null,history:await many('SELECT number,winner,outcome,ended_at FROM rounds WHERE room=? AND ended_at IS NOT NULL ORDER BY number',id)};
}
export async function submit(id:string,roundId:string,answer:unknown,u:Awaited<ReturnType<typeof identity>>,skip=false){await advance(id,u.id);const r=await memberRoom(id,u.id);const rd=await one('SELECT * FROM rounds WHERE room=? AND number=?',id,r.round);if(!rd||rd.id!==roundId||r.status!=='active')throw new GameError('The round has changed.');if(rd.ended_at)return {correct:rd.winner===u.id,closed:true};const t=now();if(!rd.started_at||t<rd.started_at)throw new GameError('The round has not started yet.');if(skip&&(r.mode!=='solo'||!u.signed))throw new GameError('Skips are available in signed-in solo play.');const s=JSON.parse(rd.snapshot) as Snapshot;
 if(r.kind==='mcq'&&await one('SELECT id FROM attempts WHERE round=? AND user=?',rd.id,u.id))throw new GameError('You have already answered this round.');
 if(skip){const n=uid();await batch([["UPDATE rounds SET ended_at=?,outcome='skipped',nonce=? WHERE id=? AND ended_at IS NULL AND (SELECT COALESCE(SUM(amount),0) FROM wallet WHERE user=?)>=5",[t,n,rd.id,u.id]],["INSERT OR IGNORE INTO wallet(id,user,amount,reason,created_at) SELECT ?,?,-5,'Skip',? WHERE EXISTS(SELECT 1 FROM rounds WHERE id=? AND nonce=?)",['skip:'+rd.id,u.id,t,rd.id,n]]]);if((await one('SELECT nonce FROM rounds WHERE id=?',rd.id)).nonce!==n)throw new GameError('You need 5 HR to skip.');return {skipped:true};}
 const correct=checkAnswer(s,answer),elapsed=t-rd.started_at,nonce=uid();
 if(!correct&&r.kind!=='mcq')return {correct:false};
 if(correct){const q:[string,any[]][]=[['UPDATE rounds SET ended_at=?,winner=?,outcome=\'solved\',nonce=? WHERE id=? AND ended_at IS NULL AND started_at<=? AND NOT EXISTS(SELECT 1 FROM attempts WHERE round=? AND user=?)',[t,u.id,nonce,rd.id,t,rd.id,u.id]],['INSERT OR IGNORE INTO attempts(id,round,user,correct,answer,elapsed,created_at) SELECT ?,?,?,1,?,?,? WHERE EXISTS(SELECT 1 FROM rounds WHERE id=? AND nonce=?)',[uid(),rd.id,u.id,JSON.stringify(answer),elapsed,t,rd.id,nonce]]];if(u.signed)q.push(["INSERT OR IGNORE INTO wallet(id,user,amount,reason,created_at) SELECT ?,?,?,'Correct answer',? WHERE EXISTS(SELECT 1 FROM rounds WHERE id=? AND nonce=?)",['reward:'+rd.id,u.id,reward(elapsed),t,rd.id,nonce]]);await batch(q);const won=(await one('SELECT winner FROM rounds WHERE id=?',rd.id))?.winner===u.id;return {correct:won,reward:won&&u.signed?reward(elapsed):0};}
 const q:[string,any[]][]=[['INSERT OR IGNORE INTO attempts(id,round,user,correct,answer,elapsed,created_at) SELECT ?,?,?,0,?,?,? WHERE EXISTS(SELECT 1 FROM rounds WHERE id=? AND ended_at IS NULL)',[uid(),rd.id,u.id,JSON.stringify(answer),elapsed,t,rd.id]]];if(r.mode==='solo')q.push(["UPDATE rounds SET ended_at=?,outcome='incorrect' WHERE id=? AND ended_at IS NULL",[t,rd.id]]);await batch(q);return {correct:false};
}
export async function dashboard(u:Awaited<ReturnType<typeof identity>>){await init();const p=await ensureProfile(u);return {profile:p,signedIn:u.signed,stats:u.signed?await one("SELECT COUNT(*) AS answered,COALESCE(SUM(correct),0) AS correct FROM attempts WHERE user=?",u.id):null,active:u.signed?await many("SELECT r.id,r.kind,r.mode,r.code FROM rooms r JOIN members m ON m.room=r.id WHERE m.user=? AND m.left_at IS NULL AND r.status IN ('waiting','active') ORDER BY r.created_at DESC",u.id):[],counts:await many('SELECT kind,locale,COUNT(*) AS n FROM content WHERE active=1 GROUP BY kind,locale')};}
